### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by WarlordX07** [SEServerExtender/SEServerExtender#101]
OS is Win Server 2008 R2

When i attempt to launch the extender I get the following error

PS C:\Steam\se\DedicatedServer64> .\SEServerExtender.exe
Finished loading LogManager
Finished loading SandboxGameAssemblyWrapper
System.TypeLoadException: Could not load type 'Sandbox.Definitions.MyDefinitionId' from assembly 'Sa
ndbox.Game, Version=0.1.5522.32807, Culture=neutral, PublicKeyToken=null'.
at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.get_IsGameStarted()
at SEModAPIInternal.Support.ApplicationLog..ctor(Boolean useGamePath)
at SEModAPIInternal.Support.LogManager.get_APILog()
AppDomain.UnhandledException - System.Exception: Failed to create API log!
at SEModAPIInternal.Support.LogManager.get_APILog()
at SEServerExtender.Program.Start(String[] args)
at SEServerExtender.Program.Main(String[] args)
System.TypeLoadException: Could not load type 'Sandbox.Definitions.MyDefinitionId' from assembly 'Sa
ndbox.Game, Version=0.1.5522.32807, Culture=neutral, PublicKeyToken=null'.
at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.get_IsGameStarted()
at SEModAPIInternal.Support.ApplicationLog..ctor(Boolean useGamePath)
at SEModAPIInternal.Support.LogManager.get_APILog()

Unhandled Exception: System.Exception: Failed to create API log!
at SEModAPIInternal.Support.LogManager.get_APILog()
at SEServerExtender.Program.Start(String[] args)
at SEServerExtender.Program.Main(String[] args)
PS C:\Steam\se\DedicatedServer64>

**Comment by rexxar-tc** [comment]
This repo hasn't been updated since October. The latest release can be found over here https://github.com/rexxar-tc/SEServerExtender/releases
