### ISSUE TITLE
SE [1.123] update not compatible with SESE

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/SEServerExtender#104]
No doubt you are aware of this, but I felt obliged to post it up anyways.

2016-02-26 02:49:16.4330|Info|SEModAPIExtensions.API.Server..ctor|Finished creating server!
2016-02-26 02:49:16.4450|Info|SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.get_Instance|Finished loading DedicatedServerAssemblyWrapper
2016-02-26 02:49:16.4450|Info|SEModAPIExtensions.API.PluginManager..ctor|Finished loading PluginManager
2016-02-26 02:49:16.4450|Info|SEModAPIInternal.API.Common.FactionsManager.get_Instance|Finished loading FactionsManager
2016-02-26 02:49:16.4450|Info|SEModAPIInternal.API.Common.EntityEventManager.get_Instance|Finished loading EntityEventManager
2016-02-26 02:49:16.4680|Info|SEModAPIExtensions.API.ChatManager..ctor|Finished loading ChatManager
2016-02-26 02:49:16.4710|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|Auto-Start enabled
2016-02-26 02:49:16.4710|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|Common instance pre-selected: 'SpaceEng-1'
2016-02-26 02:49:16.4710|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|WCF disabled
2016-02-26 02:49:16.4710|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|Autosave interval: 5
2016-02-26 02:49:16.4710|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|end parsing
2016-02-26 02:49:16.4710|Info|SEServerExtender.Program.Start|Exception - System.TypeLoadException: Could not load type 'Sandbox.Common.ObjectBuilders.MyConfigDedicatedData`1' from assembly 'VRage.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIExtensions.API.Server.StartServer()
   at SEServerExtender.Program.Start(String[] args)
    |System.TypeLoadException: Could not load type 'Sandbox.Common.ObjectBuilders.MyConfigDedicatedData`1' from assembly 'VRage.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIExtensions.API.Server.StartServer()
   at SEServerExtender.Program.Start(String[] args)

**Comment by rexxar-tc** [comment]
Yeah, we've been working on it all day, no idea when it will get fixed =\

Keen did something big deep down and I just don't know how to deal with it.
