### ISSUE TITLE
SESE Crash on start

### ISSUE THREAD

**Issue by ZilgornZeypher** [SEServerExtender/SEServerExtender#107]
2016-02-29 14:36:39.3444|Info|SEServerExtender.Program.Start|Starting SEServerExtender with 0 arguments: 
2016-02-29 14:36:39.4564|Info|SEModAPIExtensions.API.Server..ctor|Finished creating server!
2016-02-29 14:36:39.4774|Info|SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.get_Instance|Finished loading DedicatedServerAssemblyWrapper
2016-02-29 14:36:39.4894|Info|SEModAPIExtensions.API.PluginManager.get_Instance|Finished loading PluginManager
2016-02-29 14:36:39.4894|Info|SEModAPIInternal.API.Common.FactionsManager.get_Instance|Finished loading FactionsManager
2016-02-29 14:36:39.4994|Info|SEModAPIInternal.API.Common.EntityEventManager.get_Instance|Finished loading EntityEventManager
2016-02-29 14:36:39.5394|Info|SEModAPIExtensions.API.ChatManager..ctor|Finished loading ChatManager
2016-02-29 14:36:39.5394|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|WCF disabled
2016-02-29 14:36:39.5455|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|end parsing
2016-02-29 14:36:40.2524|Error|SEModAPI.API.GameInstallationInfo.GetServiceInstallPath|AppDomain.UnhandledException - System.Security.SecurityException: Requested registry access is not allowed.
   at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at SEModAPI.API.GameInstallationInfo.GetServiceInstallPath(String serviceName)
   at SEModAPI.API.GameInstallationInfo.GetCommonInstanceList()
   at SEServerExtender.SEServerExtender.SetupControls()
   at SEServerExtender.SEServerExtender..ctor(Server server)
   at SEServerExtender.Program.StartGui()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
The Zone of the assembly that failed was:
MyComputer

I have tried running as both admin and non admin credentials. Server is a Windows server 2012 R2 any other information required just ask

**Comment by CombatVolcano** [comment]
This is a solution for SharePoint but it should apply here as well:

http://blogs.technet.com/b/spsforum/archive/2011/11/02/quick-solution-5-requested-registry-access-is-not-allowed.aspx

Am not a dev just trying to help

**Comment by ZilgornZeypher** [comment]
Tried that managed to change one key to allow access but it's still getting hung up with the SILSVC in windows 2012 r2. Seems that you can't disable that or modify it in any way... digging around on google more.....

Watching Server Extender it's trying to read SILSVC registry key no Idea why but it can't get access and that is why it throws this error....
