### ISSUE TITLE
SESE Update for 1.127 doesn't start

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/SEServerExtender#110]
2016-03-25 04:42:53.3424|Info|Starting SEServerExtender with 0 arguments:
2016-03-25 04:42:53.4734|Info|Finished creating server!
2016-03-25 04:42:53.4904|Info|Finished loading DedicatedServerAssemblyWrapper
2016-03-25 04:42:53.4974|Info|Finished loading PluginManager
2016-03-25 04:42:53.4974|Info|Finished loading FactionsManager
2016-03-25 04:42:53.4974|Info|Finished loading EntityEventManager
2016-03-25 04:42:53.5374|Info|Finished loading ChatManager
2016-03-25 04:42:53.5434|Info|WCF disabled
2016-03-25 04:42:53.5434|Info|end parsing
2016-03-25 04:43:19.5339|Error|System.MissingFieldException: Field not found: 'V
Rage.Game.MyObjectBuilder_SessionSettings.GameMode'.
   at SEModAPIExtensions.API.SessionManager.UpdateSessionSettings()
   at SEModAPIExtensions.API.Server.StartServer()
    |System.MissingFieldException: Field not found: 'VRage.Game.MyObjectBuilder_
SessionSettings.GameMode'.
   at SEModAPIExtensions.API.SessionManager.UpdateSessionSettings()
   at SEModAPIExtensions.API.Server.StartServer()
2016-03-25 04:43:20.5089|Info|Finished loading SandboxGameAssemblyWrapper
2016-03-25 04:43:20.6189|Info|Finished loading PlayerManager
2016-03-25 04:43:20.6249|Info|Finished loading NetworkManager

**Comment by afinegan** [comment]
Same error for me, game wont start

**Comment by rexxar-tc** [comment]
Sorry about that, I mixed up my libraries. The latest release is working.
