### ISSUE TITLE
[v1.127.09.187-alpha] Cannot start the server

### ISSUE THREAD

**Issue by Neitronus** [SEServerExtender/SEServerExtender#112]
So here's a log i'm getting right after any attempt to start a server ith SESE. Tried with moded, unmoded, new world, old save and still getting that error. Vanilla DS works on any of those settings (modded, save etc).

```
2016-03-25 15:21:37.630 - Thread:  14 ->     Exception while loading world: Object reference not set to an instance of an object.
2016-03-25 15:21:37.630 - Thread:  14 ->        at Sandbox.Game.World.MySession.RegisterComponentsFromAssemblies()
   at Sandbox.Game.World.MySession.LoadGameDefinition(MyObjectBuilder_Checkpoint checkpoint)
   at Sandbox.Game.World.MySession.Load(String sessionPath, MyObjectBuilder_Checkpoint checkpoint, UInt64 checkpointSizeInBytes)
   at Sandbox.MySandboxGame.InitQuickLaunch()
```

**Comment by rexxar-tc** [comment]
Please post the entire log.
