### ISSUE TITLE
Crashes before it loads

### ISSUE THREAD

**Issue by AusKarlos** [SEServerExtender/SEServerExtender#115]
Server runs fine when using the dedicated exe. But i cant not start the server from the SEExtender exe.

```
2016-03-28 16:17:18.2501|Info|SEServerExtender.Program.Start|Starting SEServerExtender with 0 arguments: 
2016-03-28 16:17:18.3527|Info|SEServerExtender.Program.Start|Exception - {0}
    |System.TypeLoadException: Could not load type 'Sandbox.Definitions.MyDefinitionId' from assembly 'VRage.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIInternal.API.Server.ServerNetworkManager.ReflectionUnitTest()
   at SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests()
   at SEModAPIExtensions.API.BasicUnitTestManager.Run()
   at SEServerExtender.Program.Start(String[] args)
```

**Comment by rexxar-tc** [comment]
That kind of error happens when your SE and SESE versions are out of sync. Make sure everything's up to date.
