### ISSUE TITLE
[v1.130.12.268-alpha] Entity List disappears

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/SEServerExtender#116]
I know you got a big job sorting SESE out, and not sure if this issue has come up for you. It seems to happen if I leave SESE in entities TAB for a long time, and the only way it'll display again is a restart. Windows picks it up as an 'Unhandled Exception' and I get the choice of 'Continue or Quit'. This is not affecting server running, nor does it pause any processes.
Here is the error that is being picked up when it disappears...

*************\* Exception Text **************
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at SEServerExtender.SEServerExtender.RenderSectorObjectChildNodes(TreeNode objectsNode)
   at SEServerExtender.SEServerExtender.TreeViewRefresh(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

[Full error log here](http://pastebin.com/Hf4jLJx2)

**Comment by rexxar-tc** [comment]
Interesting. I think it's somehow caching the list of game entities, and when it tries to re-sort and hits an entity that no longer exists, it crashes. I'll see if I can't fix that in the next release.
