### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by erickuchta** [SEServerExtender/SEServerExtender#118]
Hello,

I would like a little support about a error.

Running a DS public server, populating between 10 and 30 players with last version of SEServerExtender and the Essentials plugin. The server is launched with a fully access on folder used. 

> 2016-04-25 17:12:01.6509|Error|System.Reflection.TargetInvocationException: Exce
> ption has been thrown by the target of an invocation. ---> System.AccessViolatio
> nException: Attempted to read or write protected memory. This is often an indica
> tion that other memory is corrupt.
>    at hkpWorld.stepDeltaTime(hkpWorld\* , Single )
>    at Havok.HkWorld.StepSimulation(Single timeInSec)
>    at Sandbox.Engine.Physics.MyPhysics.StepWorld(HkWorld world)
>    at Sandbox.Engine.Physics.MyPhysics.Simulate()
>    at Sandbox.Game.World.MySession.UpdateComponents()
>    at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
>    at Sandbox.MySandboxGame.Update()
>    at Sandbox.Engine.Platform.Game.UpdateInternal()
>    at Sandbox.Engine.Platform.Game.RunSingleFrame()
>    at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
>    at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
>    at Sandbox.Engine.Platform.Game.RunLoop()
>    at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashSc
> reen)
>    at VRage.Dedicated.DedicatedServer.RunInternal()
>    at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String custom
> Path, Boolean isService, Boolean showConsole)
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
>  Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
> t[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
> Attr, Binder binder, Object[] parameters, CultureInfo culture)
>    at SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.StartServer(Str
> ing instanceName, String overridePath, Boolean useConsole)
>     |System.Reflection.TargetInvocationException: Exception has been thrown by t
> he target of an invocation. ---> System.AccessViolationException: Attempted to r
> ead or write protected memory. This is often an indication that other memory is
> corrupt.
>    at hkpWorld.stepDeltaTime(hkpWorld\* , Single )
>    at Havok.HkWorld.StepSimulation(Single timeInSec)
>    at Sandbox.Engine.Physics.MyPhysics.StepWorld(HkWorld world)
>    at Sandbox.Engine.Physics.MyPhysics.Simulate()
>    at Sandbox.Game.World.MySession.UpdateComponents()
>    at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
>    at Sandbox.MySandboxGame.Update()
>    at Sandbox.Engine.Platform.Game.UpdateInternal()
>    at Sandbox.Engine.Platform.Game.RunSingleFrame()
>    at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
>    at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
>    at Sandbox.Engine.Platform.Game.RunLoop()
>    at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashSc
> reen)
>    at VRage.Dedicated.DedicatedServer.RunInternal()
>    at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String custom
> Path, Boolean isService, Boolean showConsole)
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
>  Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
> t[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
> Attr, Binder binder, Object[] parameters, CultureInfo culture)
>    at SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.StartServer(Str
> ing instanceName, String overridePath, Boolean useConsole)
> Attempted to read or write protected memory. This is often an indication that ot
> her memory is corrupt. System.AccessViolationException hkpStepResult hkpWorld.st
> epDeltaTime(hkpWorld_, Single)    at hkpWorld.stepDeltaTime(hkpWorld_ , Single )
> 
>    at Havok.HkWorld.StepSimulation(Single timeInSec)
>    at Sandbox.Engine.Physics.MyPhysics.StepWorld(HkWorld world)
>    at Sandbox.Engine.Physics.MyPhysics.Simulate()
>    at Sandbox.Game.World.MySession.UpdateComponents()
>    at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
>    at Sandbox.MySandboxGame.Update()
>    at Sandbox.Engine.Platform.Game.UpdateInternal()
>    at Sandbox.Engine.Platform.Game.RunSingleFrame()
>    at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
>    at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
>    at Sandbox.Engine.Platform.Game.RunLoop()
>    at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashSc
> reen)
>    at VRage.Dedicated.DedicatedServer.RunInternal()
>    at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String custom
> Path, Boolean isService, Boolean showConsole)
> 2016-04-25 17:12:01.6890|Info|Server has stopped running
> 2016-04-25 17:12:01.6990|Info|Unloading plugin 'f767bda5-0a8c-4813-85fd-a5a23417
> 78e8'
> 2016-04-25 17:12:01.6990|Info|Shutting down plugin: Dedicated Server Essentials
> - 1.13.6.53

I'm not sure if the error is from SEServerExtender, or Essentials, or my system configuration. I think all is good on the server config because it was running until few week without any problems, and all seems still good in this side.

Posting answer here, i got banned from seextender forum when i tryed to register (only 1 captcha mismatch then ban for flood ...  :S)

This problem is not reproduced  anymore for the moment ..

Hope this help. Let's me know if you need more information.

**Comment by rexxar-tc** [comment]
This is a bug in the game, not SESE.

**Comment by erickuchta** [comment]
Ok, thx for ur reply.

So, i will report in the good place! Bug is coming frequently now ... Server hardware is checked and ok.
