### ISSUE TITLE
Load error 

### ISSUE THREAD

**Issue by Lordicon** [SEServerExtender/SEServerExtender#12]
I have a fresh installed server with the newest Extender and Essentials from here and I am getting an error on server load.

2015-03-27 15:43:54.7273|Info|Handler Problems: 400 - System.TypeLoadException:
Could not load type 'VRage.Utils.MyStringId' from assembly 'VRage.Library, Versi
on=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIInternal.API.Entity.BaseObject..ctor(MyObjectBuilder_Base baseEnti
ty)
   at SEModAPIInternal.API.Entity.BaseEntity..ctor(MyObjectBuilder_EntityBase ba
seEntity)
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridEntity..ctor(FileI
nfo prefabFile)
   at EssentialsPlugin.ProcessHandlers.ProcessCommunication.AddGlobalRelay()
   at EssentialsPlugin.ProcessHandlers.ProcessCommunication.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()

**Comment by dodexahedron** [comment]
I know exactly the problem, then.
I'll fix this later tonight, when I'm home.

**Comment by Lordicon** [comment]
Also while clicking on the Entities tab I get spammed in console with this error.

2015-03-27 15:58:21.1439|Error|System.Reflection.TargetInvocationException: Exce
ption has been thrown by the target of an invocation. ---> System.TypeLoadExcept
ion: Could not load type 'VRage.Utils.MyStringId' from assembly 'VRage.Library,
Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIInternal.API.Entity.BaseObject..ctor(MyObjectBuilder_Base baseEnti
ty, Object backingObject)
   at SEModAPIInternal.API.Entity.BaseEntity..ctor(MyObjectBuilder_EntityBase ba
seEntity, Object backingObject)
   at SEModAPIInternal.API.Entity.Sector.SectorObject.VoxelMap..ctor(MyObjectBui
lder_VoxelMap definition, Object backingObject)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, B
inder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder bin
der, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCra
wlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binde
r binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at SEModAPIInternal.API.Entity.SectorObjectManager.LoadDynamic()

**Comment by Devlah** [comment]
Same here on all accounts.  Looking forward to tonight.   :)
