### ISSUE TITLE
v1.134.05.312-alpha - New Server Extender wont start the server 

### ISSUE THREAD

**Issue by afinegan** [SEServerExtender/SEServerExtender#120]
2016-05-12 15:05:41.8015|Error|System.Reflection.TargetInvocationException: Exce
ption has been thrown by the target of an invocation. ---> System.NullReferenceE
xception: Object reference not set to an instance of an object.
   at Sandbox.Engine.Multiplayer.MyDedicatedServerBase..ctor(MySyncLayer syncLay
er)
   at Sandbox.Engine.Multiplayer.MyDedicatedServer..ctor(IPEndPoint serverEndpoi
nt)
   at Sandbox.MySandboxGame..ctor(VRageGameServices services, String[] commandli
neArgs)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String custom
Path, Boolean isService, Boolean showConsole)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.StartServer(Str
ing instanceName, String overridePath, Boolean useConsole)
    |System.Reflection.TargetInvocationException: Exception has been thrown by t
he target of an invocation. ---> System.NullReferenceException: Object reference
 not set to an instance of an object.
   at Sandbox.Engine.Multiplayer.MyDedicatedServerBase..ctor(MySyncLayer syncLay
er)
   at Sandbox.Engine.Multiplayer.MyDedicatedServer..ctor(IPEndPoint serverEndpoi
nt)
   at Sandbox.MySandboxGame..ctor(VRageGameServices services, String[] commandli
neArgs)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String custom
Path, Boolean isService, Boolean showConsole)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.StartServer(Str
ing instanceName, String overridePath, Boolean useConsole)
Object reference not set to an instance of an object. System.NullReferenceExcept
ion Void .ctor(Sandbox.Game.Multiplayer.MySyncLayer)    at Sandbox.Engine.Multip
layer.MyDedicatedServerBase..ctor(MySyncLayer syncLayer)
   at Sandbox.Engine.Multiplayer.MyDedicatedServer..ctor(IPEndPoint serverEndpoi
nt)
   at Sandbox.MySandboxGame..ctor(VRageGameServices services, String[] commandli
neArgs)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String custom
Path, Boolean isService, Boolean showConsole)

**Comment by Roman-Cat** [comment]
++
