### ISSUE TITLE
[1.140 update] Exception occurred on startup..An item with the same key has already been added.

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/SEServerExtender#124]
2016-06-17 03:57:10.3698|Info|Exception - System.ArgumentException: An item with
 the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boo
lean add)
   at VRage.ObjectBuilders.MyObjectFactory`2.RegisterDescriptor(TAttribute descr
iptor, Type type)
   at VRage.ObjectBuilders.MyObjectFactory`2.RegisterFromAssembly(Assembly assem
bly)
   at VRage.ObjectBuilders.MyObjectBuilderSerializer.RegisterAssembliesAndLoadSe
rializers()
   at Sandbox.MySandboxGame..ctor(VRageGameServices services, String[] commandli
neArgs)
   at SEServerExtender.Program.InitSandbox(String contentpath, String instancepa
th)
   at SEServerExtender.Program.Start(String[] args)
    |System.ArgumentException: An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boo
lean add)
   at VRage.ObjectBuilders.MyObjectFactory`2.RegisterDescriptor(TAttribute descr
iptor, Type type)
   at VRage.ObjectBuilders.MyObjectFactory`2.RegisterFromAssembly(Assembly assem
bly)
   at VRage.ObjectBuilders.MyObjectBuilderSerializer.RegisterAssembliesAndLoadSe
rializers()
   at Sandbox.MySandboxGame..ctor(VRageGameServices services, String[] commandli
neArgs)
   at SEServerExtender.Program.InitSandbox(String contentpath, String instancepa
th)
   at SEServerExtender.Program.Start(String[] args)

**Comment by foogs** [comment]
![error](https://cloud.githubusercontent.com/assets/1629240/16128041/b776755c-3407-11e6-8082-1d356ffeaacb.png)

**Comment by rexxar-tc** [comment]
You're using stable branch. Build 140 doesn't work on stable, use 138.

If you want to run your server on dev, you can add this to SteamCMD to switch: +app_update 244850 -beta development
