### ISSUE TITLE
Crash on first few seconds of starting server (v.1.150.1.664)

### ISSUE THREAD

**Issue by tbankstemp** [SEServerExtender/SEServerExtender#131]
The previous version (v1.150.01.660-alpha) works but .664 does not. Thanks.

[Console Window output]

2016-08-30 20:18:50.1982|Info|SE version: 1.144.11
2016-08-30 20:18:50.2295|Info|Extender version: 1.150.1.664
2016-08-30 20:18:50.2295|Info|Detected "Stable" branch!
2016-08-30 20:18:51.682: Bind IP : 0.0.0.0:27016
Setting breakpad minidump AppID = 244850
2016-08-30 20:18:54.6998|Info|Starting SEServerExtender with 3 arguments: autostart
        autosave=5
        debug
2016-08-30 20:18:54.7058|Info|Finished loading SandboxGameAssemblyWrapper
2016-08-30 20:18:54.7058|Info|All main types passed reflection unit tests!
2016-08-30 20:18:54.7238|Info|Finished creating server!
2016-08-30 20:18:54.7238|Info|Finished loading DedicatedServerAssemblyWrapper
2016-08-30 20:18:54.7348|Info|Finished loading PluginManager
2016-08-30 20:18:54.7348|Info|Finished loading EntityEventManager
2016-08-30 20:18:54.7518|Info|Finished loading ChatManager
2016-08-30 20:18:54.7518|Info|Auto-Start enabled
2016-08-30 20:18:54.7518|Info|Debugging enabled
2016-08-30 20:18:54.7518|Info|WCF disabled
2016-08-30 20:18:54.7518|Info|Autosave interval: 5
2016-08-30 20:18:54.7668|Info|end parsing
2016-08-30 20:18:54.872: Bind IP : 0.0.0.0:27016
2016-08-30 20:18:56.4040|Info|Loading Session Settings
2016-08-30 20:18:56.9264|Error|AppDomain.UnhandledException - System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at SteamSDK.GameServer.MasterServerUpdaterThread(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at SteamSDK.GameServer.MasterServerUpdaterThread(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by rexxar-tc** [comment]
Removed 664
