### ISSUE TITLE
System.MissingFieldException: Field not found: 'Sandbox.Engine.Multiplayer.MyMultiplayer.Static'

### ISSUE THREAD

**Issue by mikebriggs2k** [SEServerExtender/SEServerExtender#138]
My server logs, and console, are being hammered with the following exception:

2017-01-28 09:55:38.8891|Error|SEModAPIInternal.API.Server.ServerNetworkManager.GetConnectedPlayers|System.MissingFieldException: Field not found: 'Sandbox.Engine.Multiplayer.MyMultiplayer.Static'.
   at SEModAPIInternal.API.Common.NetworkManager.GetNetworkManager()
   at SEModAPIInternal.API.Server.ServerNetworkManager.GetConnectedPlayers()
    |System.MissingFieldException: Field not found: 'Sandbox.Engine.Multiplayer.MyMultiplayer.Static'.
   at SEModAPIInternal.API.Common.NetworkManager.GetNetworkManager()
   at SEModAPIInternal.API.Server.ServerNetworkManager.GetConnectedPlayers()

I seem to be able to connect and use the features of SESE otherwise, but I'm constantly getting this error, and my log file is increasing in size by about 10kb per second with no players connected. If I connect, the rate of messages seems to increase.

Log:
http://pastebin.com/UZFhqsXs

**Comment by rexxar-tc** [comment]
fixed
