### ISSUE TITLE
Voxelfilename is getting to big

### ISSUE THREAD

**Issue by ToTaLReFuSeD** [SEServerExtender/SEServerExtender#139]
Hello all,

i have a problem with SESE.
in the log by the automatic save game it can not write a voxelfile from earth that has to many chars.
So it will not save the changes at the planet anymore and the most important is that the world is not saved anymore, Please advice or bug fixing

Best Regards
ToTaLReFuSeD - Dedicated server InterStellar Journey 2.0

2017-03-22 23:57:31.497 - Thread:  21 ->     Checking file access for files in target dir.
2017-03-22 23:57:33.755 - Thread:  21 ->     Failed to write voxel file 'C:\ProgramData\SpaceEngineersDedicated\InterStellarJourney\Saves\InterStellar Journey\.new\EarthLike-678338347d120000-0-0-0-0-0-0-0-1-0-0-0-0-0-0-0-0-0-1-0-0-1-1-0-0-1-0-0-0-0-0-0-0-1-0-0-0-2-1-1-0-0-1-1-0-0-1-0-0-0-0-0-0-0-1-1-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0.vx2'
2017-03-22 23:57:33.756 - Thread:  21 ->     Exception occured: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at Sandbox.Game.World.MySessionSnapshot.SaveVoxelSnapshot(String storageName, Byte[] snapshotData)

**Comment by rexxar-tc** [comment]
This is a Keen issue
