### ISSUE TITLE
Crash after using ban feature in Extender

### ISSUE THREAD

**Issue by Ragnar24** [SEServerExtender/SEServerExtender#21]
Hey Dodex,

Here is another bug that I have noticed. Don't know if it directly relates to extender or not but after I banned a player today this error popped up. If you need any more information let me know.

2015-04-23 16:42:24.380: Player dantigggg banned
2015-04-23 16:42:24.389: User left dantigggg
2015-04-23 16:42:24.399: Player  kicked
2015-04-23 16:42:24.403: User left
2015-04-23 16:42:24.403: User left
2015-04-23 16:42:24.4035|Info|Chat - Server: Banned '76561198056632510' and kick
ed them off of the server
2015-04-23 16:42:24.4735|Info|SpaceEngineers-Dedicated.cfg has changed updating
configuration settings.
2015-04-23 16:42:24.4925|Info|SpaceEngineers-Dedicated.cfg has changed updating
configuration settings.
2015-04-23 16:42:24.4735|Info|SpaceEngineers-Dedicated.cfg has changed updating
configuration settings.
2015-04-23 16:42:24.4735|Info|SpaceEngineers-Dedicated.cfg has changed updating
configuration settings.
2015-04-23 16:42:24.5055|Info|Queued Transport Removed: 76561198056632510
2015-04-23 16:42:24.5375|Info|SpaceEngineers-Dedicated.cfg has changed updating
configuration settings.
2015-04-23 16:42:24.5375|Info|SpaceEngineers-Dedicated.cfg has changed updating
configuration settings.
2015-04-23 16:42:24.771: Logging off Steam...
2015-04-23 16:42:24.771: Shutting down server...
2015-04-23 16:42:24.869: Done
2015-04-23 16:42:24.8696|Info|Server has stopped running
2015-04-23 16:42:24.8696|Info|Unloading plugin 'f767bda5-0a8c-4813-85fd-a5a23417
78e8'
2015-04-23 16:42:24.8852|Info|Shutting down plugin: Dedicated Server Essentials
- 1.12.0.2392
  2015-04-23 16:42:24.9165|Error|System.Threading.ThreadAbortException: Thread was
  being aborted.
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, U
  Int32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
  at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle,
  Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.GameAction(Action a
  ction)
  2015-04-23 16:42:24.9946|Error|System.Threading.ThreadAbortException: Thread was
  being aborted.
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.GameAction(Action a
  ction)
  at EssentialsPlugin.ProcessHandlers.ProcessGreeting.Handle()
  2015-04-23 16:42:24.9946|Info|Handler Problems: 1000 - System.Threading.ThreadAb
  ortException: Thread was being aborted.
  at EssentialsPlugin.ProcessHandlers.ProcessGreeting.Handle()
  at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()
  2015-04-23 16:42:25.0102|Error|System.Threading.ThreadAbortException: Thread was
  being aborted.
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, U
  Int32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
  at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle,
  Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.GameAction(Action a
  ction)
  2015-04-23 16:42:25.0259|Error|System.Threading.ThreadAbortException: Thread was
  being aborted.
   at EssentialsPlugin.Utility.CubeGrids.SafeGetObjectBuilder(IMyCubeGrid grid)
  at EssentialsPlugin.Utility.CubeGrids.GetGridsUnconnected(HashSet`1 connected
  List, HashSet`1 entitiesToConfirm)
  at EssentialsPlugin.EntityManagers.EntityManagement.CheckAndConcealEntities()

2015-04-23 16:42:25.0415|Info|Handler Problems: 1000 - System.Threading.ThreadAb
ortException: Thread was being aborted.
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.GameAction(Action a
ction)
   at EssentialsPlugin.ProcessHandlers.ProcessDockingZone.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()
2015-04-23 16:42:25.0415|Info|Handler Problems: 1000 - System.Threading.ThreadAb
ortException: Thread was being aborted.
   at EssentialsPlugin.EntityManagers.EntityManagement.CheckAndConcealEntities()

   at EssentialsPlugin.ProcessHandlers.ProcessConceal.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()

**Comment by dodexahedron** [comment]
That was a Space Engineers problem.
This method literally just calls ban in the game.
According to that log, you banned the person, and then the server proceeded to just shut down.
That's not SESE's fault, so I'd report that to keen.  Use the SE log from your world folder when reporting it, as the SESE log won't help them.
