### ISSUE TITLE
Missing Method Exception v1.79.8.411

### ISSUE THREAD

**Issue by tdmike** [SEServerExtender/SEServerExtender#23]
Just updated to your newest version, got the following error:

2015-04-25 17:48:08.2655|Info|Handler Problems: 10000 - System.MissingMethodException: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
   at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()
2015-04-25 17:48:18.2793|Info|Handler Problems: 10000 - System.MissingMethodException: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
   at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()
2015-04-25 17:48:28.3915|Info|Handler Problems: 10000 - System.MissingMethodException: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
   at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()
2015-04-25 17:48:38.4959|Info|Handler Problems: 10000 - System.MissingMethodException: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
   at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()
2015-04-25 17:48:48.6045|Info|Handler Problems: 10000 - System.MissingMethodException: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
   at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()
2015-04-25 17:49:00.5507|Info|Handler Problems: 10000 - System.MissingMethodException: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
   at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()

The Error keeps repeating itself although the server seems to be working fine. It also seems to save just fine.

**Comment by fo0** [comment]
got the same problems.

**Comment by dodexahedron** [comment]
This came from essentials.
Did you also update essentials?
If so, and you are still getting the error, please re-post this over on the essentials bug tracker, if you don't mind, and I'll fix it as soon as I can.

**Comment by tdmike** [comment]
re posted this in the correct tracker :)

**Comment by fo0** [comment]
i always updating everything, which is possible at this moment.
With new Update it was fixed. But Server crashing  now without any reason (at console).
Just saying stopped Server, after it was running about 5mins pretty well.
