### ISSUE TITLE
Extender 1.79.8.411- SaveWorld Method not found

### ISSUE THREAD

**Issue by Ragnar24** [SEServerExtender/SEServerExtender#24]
Hey Dodex,

Just downloaded your recent updated version of extender and after the first server save this error came up: (server crash was due to another reason)

2015-04-25 19:11:58.0644|Info|Handler Problems: 10000 - System.MissingMethodExce
ption: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorl
d()'.
   at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()

Figured you would like to know.

**Comment by xxam** [comment]
same error message here, but the server didnt crash - it just keeps on spitting out this error message.
2015-04-26 04:11:46.3504|Info|EssentialsPlugin.Essentials+<>c__DisplayClass3.<PluginProcessing>b__2|Handler Problems: 10000 - System.MissingMethodException: Method not found: 'Void SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
   at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()

**Comment by dodexahedron** [comment]
Did you happen to also update essentials?

**Comment by Ragnar24** [comment]
Continued post in Essentials issues page.
https://github.com/SEServerExtender/EssentialsPlugin/issues/30

**Comment by dodexahedron** [comment]
Clsoed in favor of SEServerExtender/EssentialsPlugin#30
