### ISSUE TITLE
System.MissingMethodException, Saving Doesnt work with 1.79.8.419

### ISSUE THREAD

**Issue by tdmike** [SEServerExtender/SEServerExtender#34]
2015-04-30 18:17:29.2385|Info|Handler Problems: 10000 - System.MissingMethodException: Met
hod not found: 'Boolean SEModAPIInternal.API.Common.WorldManager.SaveWorld()'.
   at EssentialsPlugin.ProcessHandlers.ProcessRestart.Handle()
   at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()

At the moment this is being spammed in my console, and I cant save the world anymore.

**Comment by dodexahedron** [comment]
That indicates you have not updated Essentials to 2401.
Please update Essentials to 2401 and this will go away.

**Comment by dodexahedron** [comment]
https://github.com/SEServerExtender/EssentialsPlugin/releases/tag/v1.12.0.2401-alpha
