### ISSUE TITLE
.419 not compatible with New SE 1.080

### ISSUE THREAD

**Issue by xxam** [SEServerExtender/SEServerExtender#35]
Server extender would not start up. A lot of exceptions in the logfiles

**Comment by hkraal** [comment]
+1

NoInstance-SEServerExtenderLog-2015-04-30.log:

```
2015-04-30 22:34:54.8309|Info|SEServerExtender.Program.Start|Starting SEServerExtender with 0 arguments ...
2015-04-30 22:34:55.0028|Info|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper..ctor|Finished loading SandboxGameAssemblyWrapper
2015-04-30 22:34:55.0028|Error|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.ReflectionUnitTest|System.Exception: Could not find internal type for MainGame
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.ReflectionUnitTest()
2015-04-30 22:34:55.0184|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|SandboxGameAssemblyWrapper reflection validation failed!
2015-04-30 22:34:55.0340|Error|SEModAPIInternal.API.Common.NetworkManager.PreparePacketRegistrationMethod|System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIInternal.API.Common.NetworkManager.PreparePacketRegistrationMethod()
2015-04-30 22:34:55.0340|Error|SEModAPIInternal.API.Common.NetworkManager.ReflectionUnitTest|System.Exception: Could not find internal type for NetworkManager
   at SEModAPIInternal.API.Common.NetworkManager.ReflectionUnitTest()
2015-04-30 22:34:55.0340|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|NetworkManager reflection validation failed!
2015-04-30 22:34:55.0497|Error|SEModAPIInternal.API.Server.ServerNetworkManager.ReflectionUnitTest|System.Exception: Could not find internal type for ServerNetworkManager
   at SEModAPIInternal.API.Server.ServerNetworkManager.ReflectionUnitTest()
2015-04-30 22:34:55.0497|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|ServerNetworkManager reflection validation failed!
2015-04-30 22:34:55.0653|Error|SEModAPIExtensions.API.ChatManager.ReflectionUnitTest|System.Exception: Could not find internal type for ChatMessageStruct
   at SEModAPIExtensions.API.ChatManager.ReflectionUnitTest()
2015-04-30 22:34:55.0653|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|ChatManager reflection validation failed!
2015-04-30 22:34:55.0653|Error|SEModAPIInternal.API.Common.PlayerMap.ReflectionUnitTest|System.Exception: Could not find internal type for PlayerMap
   at SEModAPIInternal.API.Common.PlayerMap.ReflectionUnitTest()
2015-04-30 22:34:55.0653|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|PlayerMap reflection validation failed!
2015-04-30 22:34:55.0809|Error|SEModAPIInternal.API.Common.PlayerManager.ReflectionUnitTest|System.Exception: Could not find internal type for PlayerManager
   at SEModAPIInternal.API.Common.PlayerManager.ReflectionUnitTest()
2015-04-30 22:34:55.0809|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|PlayerManager reflection validation failed!
2015-04-30 22:34:55.0809|Error|SEModAPIInternal.API.Common.WorldManager.ReflectionUnitTest|System.Exception: Could not find internal type for WorldManager
   at SEModAPIInternal.API.Common.WorldManager.ReflectionUnitTest()
2015-04-30 22:34:55.0809|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|WorldManager reflection validation failed!
2015-04-30 22:34:55.0809|Error|SEModAPIInternal.API.Common.RadioManager.ReflectionUnitTest|System.Exception: Could not find internal type for RadioManager
   at SEModAPIInternal.API.Common.RadioManager.ReflectionUnitTest()
2015-04-30 22:34:55.0965|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|RadioManager reflection validation failed!
2015-04-30 22:34:55.0965|Error|SEModAPIInternal.API.Common.RadioManagerNetworkManager.ReflectionUnitTest|System.Exception: Could not find internal type for RadioManagerNetworkManager
   at SEModAPIInternal.API.Common.RadioManagerNetworkManager.ReflectionUnitTest()
2015-04-30 22:34:55.0965|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|RadioManagerNetworkManager reflection validation failed!
2015-04-30 22:34:55.1122|Error|SEModAPIInternal.API.Common.PowerManager.ReflectionUnitTest|System.Exception: Could not find internal type for PowerManager
   at SEModAPIInternal.API.Common.PowerManager.ReflectionUnitTest()
2015-04-30 22:34:55.1122|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|PowerManager reflection validation failed!
2015-04-30 22:34:55.1122|Error|SEModAPIInternal.API.Common.FactionsManager.ReflectionUnitTest|System.Exception: Could not find internal type for FactionsManager
   at SEModAPIInternal.API.Common.FactionsManager.ReflectionUnitTest()
2015-04-30 22:34:55.1278|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|FactionsManager reflection validation failed!
2015-04-30 22:34:55.1278|Error|SEModAPIInternal.API.Common.Faction.ReflectionUnitTest|System.Exception: Could not find internal type for Faction
   at SEModAPIInternal.API.Common.Faction.ReflectionUnitTest()
2015-04-30 22:34:55.1278|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|Faction reflection validation failed!
2015-04-30 22:34:55.2684|Error|SEModAPIInternal.API.Entity.BaseEntity.ReflectionUnitTest|System.Exception: Could not find physics manager type for BaseEntity
   at SEModAPIInternal.API.Entity.BaseEntity.ReflectionUnitTest()
2015-04-30 22:34:55.2841|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|BaseEntity reflection validation failed!
2015-04-30 22:34:55.2841|Error|SEModAPIInternal.API.Entity.BaseEntityNetworkManager.ReflectionUnitTest|System.Exception: Could not find internal type for BaseEntityNetworkManager
   at SEModAPIInternal.API.Entity.BaseEntityNetworkManager.ReflectionUnitTest()
2015-04-30 22:34:55.2841|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|BaseEntityNetworkManager reflection validation failed!
2015-04-30 22:34:55.2997|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridNetworkManager.ReflectionUnitTest|System.Exception: Could not find internal type for CubeGridNetworkManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridNetworkManager.ReflectionUnitTest()
2015-04-30 22:34:55.2997|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|CubeGridNetworkManager reflection validation failed!
2015-04-30 22:34:55.2997|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridThrusterManager.ReflectionUnitTest|System.Exception: Could not find type for CubeGridThrusterManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridThrusterManager.ReflectionUnitTest()
2015-04-30 22:34:55.3153|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|CubeGridThrusterManager reflection validation failed!
2015-04-30 22:34:55.3153|Error|SEModAPIInternal.API.Entity.SectorObjectManager.ReflectionUnitTest|System.Exception: Could not find object factory type for SectorObjectManager
   at SEModAPIInternal.API.Entity.SectorObjectManager.ReflectionUnitTest()
2015-04-30 22:34:55.3153|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|SectorObjectManager reflection validation failed!
2015-04-30 22:34:55.3309|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CharacterEntity.ReflectionUnitTest|System.Exception: Could not find battery type for CharacterEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CharacterEntity.ReflectionUnitTest()
2015-04-30 22:34:55.3309|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|CharacterEntity reflection validation failed!
2015-04-30 22:34:55.3466|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CharacterEntityNetworkManager.ReflectionUnitTest|System.Exception: Could not find internal type for CharacterEntityNetworkManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CharacterEntityNetworkManager.ReflectionUnitTest()
2015-04-30 22:34:55.3466|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|CharacterEntityNetworkManager reflection validation failed!
2015-04-30 22:34:55.3466|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.FloatingObjectManager.ReflectionUnitTest|System.Exception: Could not find internal type for FloatingObjectManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.FloatingObjectManager.ReflectionUnitTest()
2015-04-30 22:34:55.3622|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|FloatingObjectManager reflection validation failed!
2015-04-30 22:34:55.3622|Error|SEModAPIInternal.API.Entity.InventoryEntity.ReflectionUnitTest|System.Exception: Could not find internal type for InventoryEntity
   at SEModAPIInternal.API.Entity.InventoryEntity.ReflectionUnitTest()
2015-04-30 22:34:55.3622|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|InventoryEntity reflection validation failed!
2015-04-30 22:34:55.3778|Error|SEModAPIInternal.API.Entity.InventoryItemEntity.ReflectionUnitTest|System.Exception: Could not find internal type for InventoryItemEntity
   at SEModAPIInternal.API.Entity.InventoryItemEntity.ReflectionUnitTest()
2015-04-30 22:34:55.3778|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|InventoryItemEntity reflection validation failed!
2015-04-30 22:34:55.3778|Error|SEModAPIInternal.API.Entity.PowerProducer.ReflectionUnitTest|System.TypeLoadException: Could not find internal type for PowerProducer
   at SEModAPIInternal.API.Entity.PowerProducer.ReflectionUnitTest()
2015-04-30 22:34:55.3778|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|PowerProducer reflection validation failed!
2015-04-30 22:34:55.3934|Error|SEModAPIInternal.API.Entity.PowerReceiver.ReflectionUnitTest|System.Exception: Could not find internal type for PowerReceiver
   at SEModAPIInternal.API.Entity.PowerReceiver.ReflectionUnitTest()
2015-04-30 22:34:55.3934|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|PowerReceiver reflection validation failed!
2015-04-30 22:34:55.4091|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlockEntity.ReflectionUnitTest|System.Exception: Could not find internal type for CubeBlockEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlockEntity.ReflectionUnitTest()
2015-04-30 22:34:55.4091|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|CubeBlockEntity reflection validation failed!
2015-04-30 22:34:55.4247|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ProductionBlockEntity.ReflectionUnitTest|System.Exception: Could not find internal type for ProductionBlockEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ProductionBlockEntity.ReflectionUnitTest()
2015-04-30 22:34:55.4247|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|ProductionBlockEntity reflection validation failed!
2015-04-30 22:34:55.4403|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.LightEntity.ReflectionUnitTest|System.Exception: Could not find internal type for LightEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.LightEntity.ReflectionUnitTest()
2015-04-30 22:34:55.4403|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|LightEntity reflection validation failed!
2015-04-30 22:34:55.4559|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.BatteryBlockEntity.ReflectionUnitTest|System.Exception: Could not find internal type for BatteryBlockEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.BatteryBlockEntity.ReflectionUnitTest()
2015-04-30 22:34:55.4559|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|BatteryBlockEntity reflection validation failed!
2015-04-30 22:34:55.4559|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.BatteryBlockNetworkManager.ReflectionUnitTest|System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.BatteryBlockNetworkManager.get_InternalType()
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.BatteryBlockNetworkManager.ReflectionUnitTest()
2015-04-30 22:34:55.4559|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|BatteryBlockNetworkManager reflection validation failed!
2015-04-30 22:34:55.4719|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.DoorEntity.ReflectionUnitTest|System.Exception: Could not find internal type for DoorEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.DoorEntity.ReflectionUnitTest()
2015-04-30 22:34:55.4719|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|DoorEntity reflection validation failed!
2015-04-30 22:34:55.4719|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.GravityBaseEntity.ReflectionUnitTest|System.Exception: Could not find internal type for GravityBaseEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.GravityBaseEntity.ReflectionUnitTest()
2015-04-30 22:34:55.4872|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|GravityBaseEntity reflection validation failed!
2015-04-30 22:34:55.4872|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.GravitySphereEntity.ReflectionUnitTest|System.Exception: Could not find internal type for GravitySphereEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.GravitySphereEntity.ReflectionUnitTest()
2015-04-30 22:34:55.5028|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|GravitySphereEntity reflection validation failed!
2015-04-30 22:34:55.5028|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.BeaconEntity.ReflectionUnitTest|System.Exception: Could not find internal type for BeaconEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.BeaconEntity.ReflectionUnitTest()
2015-04-30 22:34:55.5028|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|BeaconEntity reflection validation failed!
2015-04-30 22:34:55.5028|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.AntennaEntity.ReflectionUnitTest|System.Exception: Could not find internal type for AntennaEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.AntennaEntity.ReflectionUnitTest()
2015-04-30 22:34:55.5184|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|AntennaEntity reflection validation failed!
2015-04-30 22:34:55.5184|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ThrustEntity.ReflectionUnitTest|System.Exception: Could not find internal type for ThrustEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ThrustEntity.ReflectionUnitTest()
2015-04-30 22:34:55.5184|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|ThrustEntity reflection validation failed!
2015-04-30 22:34:55.5340|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ThrustNetworkManager.ReflectionUnitTest|System.Exception: Could not find network manager type for ThrustEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ThrustNetworkManager.ReflectionUnitTest()
2015-04-30 22:34:55.5340|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|ThrustNetworkManager reflection validation failed!
2015-04-30 22:34:55.5340|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.GyroEntity.ReflectionUnitTest|System.Exception: Could not find internal type for GyroEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.GyroEntity.ReflectionUnitTest()
2015-04-30 22:34:55.5340|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|GyroEntity reflection validation failed!
2015-04-30 22:34:55.5497|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.GyroNetworkManager.ReflectionUnitTest|System.Exception: Could not find internal type for GyroNetworkManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.GyroNetworkManager.ReflectionUnitTest()
2015-04-30 22:34:55.5497|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|GyroNetworkManager reflection validation failed!
2015-04-30 22:34:55.5497|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.CockpitEntity.ReflectionUnitTest|System.TypeLoadException: Could not find type for CockpitEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.CockpitEntity.ReflectionUnitTest()
2015-04-30 22:34:55.5653|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|CockpitEntity reflection validation failed!
2015-04-30 22:34:55.5653|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.TurretNetworkManager.ReflectionUnitTest|System.Exception: Could not find internal type for TurretNetworkManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.TurretNetworkManager.ReflectionUnitTest()
2015-04-30 22:34:55.5809|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|TurretNetworkManager reflection validation failed!
2015-04-30 22:34:55.5809|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.LandingGearEntity.ReflectionUnitTest|System.Exception: Could not find internal type for LandingGearEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.LandingGearEntity.ReflectionUnitTest()
2015-04-30 22:34:55.5809|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|LandingGearEntity reflection validation failed!
2015-04-30 22:34:55.5966|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.LandingGearNetworkManager.ReflectionUnitTest|System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.LandingGearNetworkManager.ReflectionUnitTest()
2015-04-30 22:34:55.5966|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|LandingGearNetworkManager reflection validation failed!
2015-04-30 22:34:55.5966|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ReactorEntity.ReflectionUnitTest|System.Exception: Could not find internal type for ReactorEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ReactorEntity.ReflectionUnitTest()
2015-04-30 22:34:55.5966|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|ReactorEntity reflection validation failed!
2015-04-30 22:34:55.5966|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.SolarPanelEntity.ReflectionUnitTest|System.Exception: Could not find internal type for SolarPanelEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.SolarPanelEntity.ReflectionUnitTest()
2015-04-30 22:34:55.6122|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|SolarPanelEntity reflection validation failed!
2015-04-30 22:34:55.6122|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.MergeBlockEntity.ReflectionUnitTest|System.Exception: Could not find internal type for MergeBlockEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.MergeBlockEntity.ReflectionUnitTest()
2015-04-30 22:34:55.6122|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|MergeBlockEntity reflection validation failed!
2015-04-30 22:34:55.6278|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.PistonEntity.ReflectionUnitTest|System.Exception: Could not find internal type for PistonEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.PistonEntity.ReflectionUnitTest()
2015-04-30 22:34:55.6278|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|PistonEntity reflection validation failed!
2015-04-30 22:34:55.6278|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.PistonNetworkManager.ReflectionUnitTest|System.Exception: Could not find internal type for PistonNetworkManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.PistonNetworkManager.ReflectionUnitTest()
2015-04-30 22:34:55.6278|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|PistonNetworkManager reflection validation failed!
2015-04-30 22:34:55.6434|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.RotorEntity.ReflectionUnitTest|System.Exception: Could not find internal type for RotorEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.RotorEntity.ReflectionUnitTest()
2015-04-30 22:34:55.6434|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|RotorEntity reflection validation failed!
2015-04-30 22:34:55.6434|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.CameraBlockEntity.ReflectionUnitTest|System.Exception: Could not find internal type for CameraBlockEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.CameraBlockEntity.ReflectionUnitTest()
2015-04-30 22:34:55.6591|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|CameraBlockEntity reflection validation failed!
2015-04-30 22:34:55.6591|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.OreDetectorEntity.ReflectionUnitTest|System.Exception: Could not find internal type for OreDetectorEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.OreDetectorEntity.ReflectionUnitTest()
2015-04-30 22:34:55.6591|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|OreDetectorEntity reflection validation failed!
2015-04-30 22:34:55.6591|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ButtonPanelEntity.ReflectionUnitTest|System.TypeLoadException: Could not find internal type for ButtonPanelEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ButtonPanelEntity.ReflectionUnitTest()
2015-04-30 22:34:55.6747|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|ButtonPanelEntity reflection validation failed!
2015-04-30 22:34:55.6747|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ShipControllerEntity.ReflectionUnitTest|System.Exception: Could not find type for ShipControllerEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ShipControllerEntity.ReflectionUnitTest()
2015-04-30 22:34:55.6747|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|ShipControllerEntity reflection validation failed!
2015-04-30 22:34:55.6747|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ShipControllerNetworkManager.ReflectionUnitTest|System.Exception: Could not find type for ShipControllerNetworkManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ShipControllerNetworkManager.ReflectionUnitTest()
2015-04-30 22:34:55.6747|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|ShipControllerNetworkManager reflection validation failed!
2015-04-30 22:34:55.6903|Info|SEModAPIExtensions.API.Server..ctor|Finished creating server!
2015-04-30 22:34:55.7059|Info|SEModAPIInternal.API.Server.ServerAssemblyWrapper.get_Instance|Finished loading ServerAssemblyWrapper
2015-04-30 22:34:55.7059|Info|SEModAPIExtensions.API.PluginManager..ctor|Finished loading PluginManager
2015-04-30 22:34:55.7218|Info|SEModAPIInternal.API.Common.FactionsManager.get_Instance|Finished loading FactionsManager
2015-04-30 22:34:55.7218|Info|SEModAPIInternal.API.Common.EntityEventManager.get_Instance|Finished loading EntityEventManager
2015-04-30 22:34:55.7713|Info|SEModAPIExtensions.API.ChatManager..ctor|Finished loading ChatManager
2015-04-30 22:34:55.7840|Info|SEServerExtender.Program.Start|Opening up WCF service listener at http://localhost:5353/ServerService/
2015-04-30 22:34:55.9872|Error|SEServerExtender.SEServerExtender..ctor|AppDomain.UnhandledException - System.MissingMethodException: Method not found: 'Sandbox.Common.ObjectBuilders.MyConfigDedicatedData SEModAPIExtensions.API.Server.LoadServerConfig()'.
   at SEServerExtender.SEServerExtender..ctor(Server server)
   at SEServerExtender.Program.StartGui()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by dodexahedron** [comment]
Yes, I'm pretty well aware of this one.
There was a HUGE change to Space Engineers, this week.
I have just finished updating it and the release will be available in a couple minutes.

**Comment by hkraal** [comment]
@dodexahedron Release is working indeed, server is starting again. Awesome job, thank you so much for keeping it up!
