### ISSUE TITLE
Extender 1.83.8.490 With SE 1.084

### ISSUE THREAD

**Issue by xxam** [SEServerExtender/SEServerExtender#51]
Extender 1.83.8.490 With SE 1.084 is not working.

Something with VRage Libs not found - and clicking on the entity tab will let it rain error messages.

**Comment by wweiland** [comment]
concurred

**Comment by DigTron** [comment]
The error in question.

```
2015-05-28 17:24:01.3287|Info|Handler Problems: 400 - System.TypeLoadException:
Could not load type 'VRage.Library.Utils.MyStringId' from assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
  at SEModAPIInternal.API.Entity.BaseObject..ctor(MyObjectBuilder_Base baseEntity)
  at SEModAPIInternal.API.Entity.BaseEntity..ctor(MyObjectBuilder_EntityBase baseEntity)
  at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridEntity..ctor(FileInfo prefabFile)
  at EssentialsPlugin.ProcessHandlers.ProcessCommunication.AddGlobalRelay()
  at EssentialsPlugin.ProcessHandlers.ProcessCommunication.Handle()
  at EssentialsPlugin.Essentials.<>c__DisplayClass3.<PluginProcessing>b__2()
```

And one that results from selecting the entities tab. When selected, spams repeatedly until a different tab is selected.

```
2015-05-28 17:49:04.9243|Error|System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'VRage.Library.Utils.MyStringId' from assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
  at SEModAPIInternal.API.Entity.BaseObject..ctor(MyObjectBuilder_Base baseEntity, Object backingObject)
  at SEModAPIInternal.API.Entity.BaseEntity..ctor(MyObjectBuilder_EntityBase baseEntity, Object backingObject)
  at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridEntity..ctor(MyObjectBuilder_CubeGrid definition, Object backingObject)
  --- End of inner exception stack trace ---
  at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
  at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
  at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
  at System.Activator.CreateInstance(Type type, Object[] args)
  at SEModAPIInternal.API.Entity.SectorObjectManager.LoadDynamic()
```

Also no sure if its because of extender or not but essentials chat commands do not appear to be working.

**Comment by DigTron** [comment]
Come to think of it, I think that first error is from Essentials and not Extender.

**Comment by qrokodial** [comment]
yeah, it needs an update to include the latest binaries, just be patient.

**Comment by dodexahedron** [comment]
This is fixed in https://github.com/SEServerExtender/SEServerExtender/releases/tag/v1.84.10.491-alpha
