### ISSUE TITLE
sporadic Servercrash extender 1.84.10.491 with SE 1.084.11

### ISSUE THREAD

**Issue by xxam** [SEServerExtender/SEServerExtender#53]
sporadic Servercrash extender 1.84.10.491 with SE 1.084.11
this is the responding log entry:
2015-05-30 17:10:32.1078|Error|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.GameAction|System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.GameAction(Action action)

**Comment by dodexahedron** [comment]
Thread aborts are usually caused by a game bug or a faulty mod.
Check the mods you have installed - that's the most likely culprit.

**Comment by dodexahedron** [comment]
Closing this.
Please open a new one if it still happens on the newest release and with all mods disabled.
