### ISSUE TITLE
1.085 Update breaks Server Extender

### ISSUE THREAD

**Issue by DjKiDD** [SEServerExtender/SEServerExtender#55]
2015-06-04 10:51:00.6626|Info|SEServerExtender.Program.Start|Exception - {0}
    |System.TypeLoadException: Could not load type 'Sandbox.Definitions.MyDefinitionId' from assembly 'Sandbox.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.ReflectionUnitTest()
   at SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests()
   at SEModAPIExtensions.API.BasicUnitTestManager.Run()
   at SEServerExtender.Program.Start(String[] args)
2015-06-04 10:51:15.5077|Info|SEServerExtender.Program.Start|Exception - {0}
    |System.TypeLoadException: Could not load type 'Sandbox.Definitions.MyDefinitionId' from assembly 'Sandbox.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.ReflectionUnitTest()
   at SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests()
   at SEModAPIExtensions.API.BasicUnitTestManager.Run()
   at SEServerExtender.Program.Start(String[] args)

**Comment by johskar** [comment]
Getting the same error as well.

**Comment by dodexahedron** [comment]
Will fix shortly

**Comment by dodexahedron** [comment]
Re-opening this and closing #56, as this is the original issue.

**Comment by dodexahedron** [comment]
This is now fixed and will be released shortly.
