### ISSUE TITLE
1.086 Update breaks Server Extender

### ISSUE THREAD

**Issue by DjKiDD** [SEServerExtender/SEServerExtender#61]
2015-06-11 15:04:28.6542|Info|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper..ctor|Finished loading SandboxGameAssemblyWrapper
2015-06-11 15:04:28.6698|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|SandboxGameAssemblyWrapper reflection validation failed!
2015-06-11 15:04:28.7948|Info|SEServerExtender.Program.Start|Exception - {0}
    |System.TypeLoadException: Method 'get_ProductionEnabled' in type 'SEModAPIInternal.API.Entity.PowerProducer' from assembly 'SEModAPIInternal, Version=1.85.8.538, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests()
   at SEModAPIExtensions.API.BasicUnitTestManager.Run()
   at SEServerExtender.Program.Start(String[] args)

**Comment by MescalineMonkey** [comment]
Same error in my server.

**Comment by dodexahedron** [comment]
Fixed in version 1.86.8.527, to be released shortly.

**Comment by DjKiDD** [comment]
You're the best dodexahedron! All your work is greatly appreciated!!!
