### ISSUE TITLE
Kick/Ban Crashes SESE Client. 

### ISSUE THREAD

**Issue by Chuuthulhu** [SEServerExtender/SEServerExtender#63]
Kicking or Banning a player via the Extender client causes a fatal exception and brings the server down. 

If it is a ban, the SteamID still gets added to the settings, but the server must be restarted. 
The error that happens in the logs is: 

2015-06-12 19:02:21.8076|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass8.<AsynchronousSaveWorld>b__7|Asynchronous Save Setup Started: 125ms
2015-06-12 19:02:23.2617|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass8.<AsynchronousSaveWorld>b__5|Asynchronous Save Completed: 1579.1015ms
2015-06-12 19:02:26.5322|Info|SEModAPIExtensions.API.Server.RunServer|Server has stopped running
2015-06-12 19:02:26.5478|Info|SEModAPIExtensions.API.PluginManager.UnloadPlugin|Unloading plugin '6fd6ab07-fb0d-4227-b770-f187571bc3a1'
2015-06-12 19:02:26.5634|Info|SEModAPIExtensions.API.PluginManager.UnloadPlugin|Unloading plugin 'f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-06-12 19:02:26.5791|Error|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.GameAction|System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.GameAction(Action action)

**Comment by dodexahedron** [comment]
This likely is a thread safety issue.
I think, back when I changed these methods, I was entrusting that the KSH mod API would perform its actions in a thread-safe manner.  It doesn't.
I'll have to put back in the code to force these operations to the game thread.  That'll most likely fix it.

**Comment by dodexahedron** [comment]
This is fixed in 531, which is available now.

**Comment by Chuuthulhu** [comment]
Fantastic, thank you so much! We've had a run of hackers this weekend on my server, so this will  prevent the need to take the whole server down in order to ban them every time.

**Comment by SilentSymphony** [comment]
Yeah dodex thanks for taking the time.
