### ISSUE TITLE
Crash on Startup, unable to start.

### ISSUE THREAD

**Issue by mawh1** [SEServerExtender/SEServerExtender#64]
Hello again Dodex : ) 

Recent update appears to have broken extender, it puts this exception into the log: 

11:09:36.1428|Error|SEModAPIExtensions.API.PluginManager.InitPlugin|System.IO.FileLoadException: Could not load file or assembly 'NLog, Version=3.2.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'NLog, Version=3.2.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'
   at System.Signature.GetSignature(Void\* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeFieldInfo fieldHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.get_FieldType()
   at System.Reflection.RtFieldInfo.get_InvocationFlags()
   at System.Reflection.RtFieldInfo.InternalSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture, StackCrawlMark& stackMark)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at SEModAPIExtensions.API.PluginManager.InitPlugin(Guid key)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2015-06-13 

Best regards,
Marek

**Comment by dodexahedron** [comment]
That indicates you are using an old version of a plugin. Update all your plugins and you should be ok

-----Original Message-----

**Comment by dodexahedron** [comment]
To clarify, Extender updated to NLog 3.2.1.0 a few versions ago, and plugins had to be recompiled using the same version.
Any plugins that still are compiled against NLog 3.2.0.0 will not load properly, any more, unless you also update them to versions which have been updated to NLog 3.2.1.0 as well.
All of the plugins I maintain have been updated since then, so if you update Essentials and GetOutOfMySandbox to the latest available, you should be ok.
