### ISSUE TITLE
SESE Crashes on startup

### ISSUE THREAD

**Issue by Ragonz2** [SEServerExtender/SEServerExtender#67]
Start command: SEServerExtender.exe nogui no
console  autostart gamepath=C:\Pingperfect\Users#####\2445\ instance=C:\Pingpe
rfect\Users#####\2445\

Error: C:\Pingperfect\Users#####\2445\DedicatedServer64>SEServerExtender.exe nogui no
console  autostart gamepath=C:\Pingperfect\Users#####\2445\ instance=C:\Pingpe
rfect\Users#####\2445\
Finished loading LogManager
System.TypeLoadException: Could not load type 'VRage.Common.Utils.MyFileSystem'
from assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=n
ull'.
   at SEModAPIInternal.Support.ApplicationLog..ctor(Boolean useGamePath)
   at SEModAPIInternal.Support.LogManager.get_APILog()
AppDomain.UnhandledException - System.Exception: Failed to create API log!
   at SEModAPIInternal.Support.LogManager.get_APILog()
   at SEServerExtender.Program.Start(String[] args)
   at SEServerExtender.Program.Main(String[] args)
System.TypeLoadException: Could not load type 'VRage.Common.Utils.MyFileSystem'
from assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=n
ull'.
   at SEModAPIInternal.Support.ApplicationLog..ctor(Boolean useGamePath)
   at SEModAPIInternal.Support.LogManager.get_APILog()

Unhandled Exception: System.Exception: Failed to create API log!
   at SEModAPIInternal.Support.LogManager.get_APILog()
   at SEServerExtender.Program.Start(String[] args)
   at SEServerExtender.Program.Main(String[] args)

**Comment by dodexahedron** [comment]
Please update to the latest release of SE, SESE, and all plugins.
This type moved several versions ago and this particular problem was fixed with that version (don't remember which).
