### ISSUE TITLE
[solved close me]SE Extender crashes when a user logs in.

### ISSUE THREAD

**Issue by afinegan** [SEServerExtender/SEServerExtender#75]
error

```
Failed to invoke entity method 'Init' on type 'Sa
ndbox.Game.Entities.MyCubeGrid': Exception has been thrown by the target of an i
nvocation.
```

Whole Thing

```
2015-07-16 15:11:53.2524|Error|Failed to invoke entity method 'Init' on type 'Sa
ndbox.Game.Entities.MyCubeGrid': Exception has been thrown by the target of an i
nvocation.
2015-07-16 15:11:53.2524|Error|System.Reflection.TargetInvocationException: Exce
ption has been thrown by the target of an invocation. ---> System.ArgumentExcept
ion: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boo
lean add)
   at Sandbox.Game.Entities.MyEntity.set_EntityId(Int64 value)
   at Sandbox.Game.Entities.MyEntity.Init(MyObjectBuilder_EntityBase objectBuild
er)
   at Sandbox.Game.Entities.MyCubeGrid.InitInternal(MyObjectBuilder_EntityBase o
bjectBuilder, Boolean rebuildGrid)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.Entity.BaseObject.InvokeEntityMethod(Object gameEntit
y, String methodName, Object[] parameters, Type[] argTypes)
2015-07-16 15:11:53.2524|Error|Failed to invoke static method 'Add': Exception h
as been thrown by the target of an invocation.
2015-07-16 15:11:53.2604|Error|System.Reflection.TargetInvocationException: Exce
ption has been thrown by the target of an invocation. ---> System.NullReferenceE
xception: Object reference not set to an instance of an object.
   at Sandbox.Game.Entities.MyCubeGrid.OnAddedToGroup(MyGridLogicalGroupData gro
up)
   at VRage.Groups.MyGroups`2.Node.set_m_group(Group value)
   at VRage.Groups.MyGroups`2.AddNode(TNode nodeToAdd)
   at Sandbox.Game.Entities.MyCubeGrid.OnAddedToScene(Object source)
   at Sandbox.Game.Entities.MyEntities.Add(MyEntity entity, Boolean insertIntoSc
ene)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.Entity.BaseObject.InvokeStaticMethod(Type objectType,
 String methodName, Object[] parameters)
2015-07-16 15:11:53.2604|Error|Failed to invoke entity method 'GetObjectBuilder'
 on type 'Sandbox.Game.Entities.MyCubeGrid': Exception has been thrown by the ta
rget of an invocation.
2015-07-16 15:11:53.2604|Error|System.Reflection.TargetInvocationException: Exce
ption has been thrown by the target of an invocation. ---> System.NullReferenceE
xception: Object reference not set to an instance of an object.
   at Sandbox.Game.Entities.MyCubeGrid.GetObjectBuilderInternal(MyObjectBuilder_
CubeGrid ob, Boolean copy)
   at Sandbox.Game.Entities.MyCubeGrid.GetObjectBuilder(Boolean copy)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.Entity.BaseObject.InvokeEntityMethod(Object gameEntit
y, String methodName, Object[] parameters, Type[] argTypes)
2015-07-16 15:11:53.472: Logging off Steam...
2015-07-16 15:11:53.473: Shutting down server...
2015-07-16 15:11:53.501: Done
```

**Comment by afinegan** [comment]
I found out this doesnt happen with a new map, but an old one

**Comment by afinegan** [comment]
Ok, I loaded map into Midspace's utility, hit save, then the server all loaded it up correctly and it works.
