### ISSUE TITLE
issue starting with Update 01.092

### ISSUE THREAD

**Issue by SilentSymphony** [SEServerExtender/SEServerExtender#76]
pretty much i get this on launch http://puu.sh/ja8nJ/f894972388.png

**Comment by afinegan** [comment]
Same thing, I turned on the fusion logging and I get this now

```
2015-07-23 14:53:23.7295|Info|Starting SEServerExtender with 4 arguments: autosa
ve=15
        autostart
        gamedir=C:\Program Files (x86)\Steam\SteamApps\common\SpaceEngineers\Ded
icatedServer64
        instance=actionpacked
2015-07-23 14:53:23.8125|Info|Finished loading SandboxGameAssemblyWrapper
2015-07-23 14:53:23.8555|Info|All main types passed reflection unit tests!
2015-07-23 14:53:23.8645|Info|Exception - {0}
    |System.IO.FileNotFoundException: Could not load file or assembly 'Sandbox.C
ommon.XmlSerializers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or
one of its dependencies. The system cannot find the file specified.
File name: 'Sandbox.Common.XmlSerializers, Version=1.0.0.0, Culture=neutral, Pub
licKeyToken=null'
   at SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests()

   at SEModAPIExtensions.API.BasicUnitTestManager.Run()
   at SEServerExtender.Program.Start(String[] args)

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\c
lr.dll
Running under executable  C:\Program Files (x86)\Steam\SteamApps\common\SpaceEng
ineers\DedicatedServer64\SEServerExtender.exe
--- A detailed error log follows.

=== Pre-bind state information ===
LOG: DisplayName = Sandbox.Common.XmlSerializers, Version=1.0.0.0, Culture=neutr
al, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Steam/SteamApps/common/SpaceEngine
ers/DedicatedServer64/
LOG: Initial PrivatePath = NULL
Calling assembly : SEModAPIInternal, Version=1.88.11.589, Culture=neutral, Publi
cKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files (x86)\Steam\SteamApp
s\common\SpaceEngineers\DedicatedServer64\SEServerExtender.exe.Config
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\
v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partia
l, or location-based assembly bind).
LOG: The same bind was seen before, and was failed with hr = 0x80070002.


```

**Comment by GlassyAndroid** [comment]
The same problem.

**Comment by MescalineMonkey** [comment]
Same here.
http://i.imgur.com/bzBZUlJ.jpg

**Comment by SilentSymphony** [comment]
http://forums.keenswh.com/threads/se-server-extender-current-releases-and-plugins.7333303/page-12#post-1286806244 fix available in this post, My server is running fine (for now)

**Comment by GlassyAndroid** [comment]
I was installed that fix and have new problem on startup:

2015-07-24 13:12:29.3177|Warn|CharacterEntity reflection validation failed!

and autosave was disabled.

**Comment by dodexahedron** [comment]
Fix for this is coming in version 558
