### ISSUE TITLE
Selecting concealed entity in Entities Window causes NullReferenceException

### ISSUE THREAD

**Issue by fo0** [SEServerExtender/SEServerExtender#8]
This error messages coming up during the running ... while nothing special happens

2015-03-24 17:44:21.0322|Error|Failed to get entity field '=F3vjA1VbQZ6h5a0yRFs7
eUEDKm='
2015-03-24 17:44:21.1132|Error|System.NullReferenceException: Der Objektverweis
wurde nicht auf eine Objektinstanz festgelegt.
   bei SEModAPIInternal.API.Entity.BaseObject.GetEntityField(Object gameEntity,
String fieldName)
2015-03-24 17:44:21.1132|Error|System.NullReferenceException: Der Objektverweis
wurde nicht auf eine Objektinstanz festgelegt.
   bei SEModAPIInternal.API.Common.PowerManager.get_TotalPower()
2015-03-24 17:44:21.1132|Error|Failed to get entity method 'get_TotalRequiredInp
ut': Game entity was null
2015-03-24 17:44:21.1132|Error|System.Exception: Game entity was null
   bei SEModAPIInternal.API.Entity.BaseObject.GetEntityMethod(Object gameEntity,
 String methodName)

**Comment by EngineerBean** [comment]
I get this error when highlighting entities that have been concealed.

**Comment by dodexahedron** [comment]
I can't comment on concealment, yet, as I haven't looked into that code at all, and it never worked properly for me, even before I forked SESE (always caused my servers to crash).
I'll eventually look into concealment, but that's a good data point.

@fo0, can you confirm if you are using entity concealment?

**Comment by fo0** [comment]
yes i can confirm that i use it, its hardly needed to proof performance, i nearly using everything what the extender gives you.

**Comment by dodexahedron** [comment]
Hmm.. Ok. After I fix the argument parsing problems for the scans (and anything that relies on them), I'll have to look into concealment as the next work item for Essentials.

**Comment by Lordicon** [comment]
I am returning this error not sure if its related or not. 

2015-03-28 16:44:54.4294|Error|Failed to get entity field '=F3vjA1VbQZ6h5a0yRFs7
eUEDKm='
2015-03-28 16:44:54.4294|Error|System.NullReferenceException: Object reference n
ot set to an instance of an object.
   at SEModAPIInternal.API.Entity.BaseObject.GetEntityField(Object gameEntity, S
tring fieldName)
2015-03-28 16:44:54.4294|Error|System.NullReferenceException: Object reference n
ot set to an instance of an object.
   at SEModAPIInternal.API.Common.PowerManager.get_TotalPower()
2015-03-28 16:44:54.4294|Error|Failed to get entity method 'get_TotalRequiredInp
ut': Game entity was null
2015-03-28 16:44:54.4294|Error|System.Exception: Game entity was null
   at SEModAPIInternal.API.Entity.BaseObject.GetEntityMethod(Object gameEntity,
String methodName)
2015-03-28 16:44:54.4294|Error|System.NullReferenceException: Object reference n
ot set to an instance of an object.
   at SEModAPIInternal.API.Entity.BaseObject.InvokeEntityMethod(Object gameEntit
y, String methodName, Object[] parameters, Type[] argTypes)
   at SEModAPIInternal.API.Common.PowerManager.get_AvailablePower()

**Comment by dodexahedron** [comment]
Are you still getting this error?
That field definitely exists in the current version of SpaceEngineers.

**Comment by fo0** [comment]
Server just crashed and got this message:

2015-04-10 16:10:05.6904|Error|Failed to get entity field '=F3vjA1VbQZ6h5a0yRFs7eUEDKm='
2015-04-10 16:10:05.6904|Error|System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SEModAPIInternal.API.Entity.BaseObject.GetEntityField(Object gameEntity, String fieldName)
2015-04-10 16:10:05.6904|Error|System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SEModAPIInternal.API.Common.PowerManager.get_TotalPower()
2015-04-10 16:10:05.7021|Error|Failed to get entity method 'get_TotalRequiredInput': Game entity was null
2015-04-10 16:10:05.7021|Error|System.Exception: Game entity was null
   bei SEModAPIInternal.API.Entity.BaseObject.GetEntityMethod(Object gameEntity, String methodName)
2015-04-10 16:10:05.7021|Error|System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SEModAPIInternal.API.Entity.BaseObject.InvokeEntityMethod(Object gameEntity, String methodName, Object[] parameters, Type[] argTypes)
   bei SEModAPIInternal.API.Common.PowerManager.get_AvailablePower()
2015-04-10 16:10:05.7021|Error|Failed to get entity field '=F3vjA1VbQZ6h5a0yRFs7eUEDKm='
2015-04-10 16:10:05.7187|Error|System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SEModAPIInternal.API.Entity.BaseObject.GetEntityField(Object gameEntity, String fieldName)
2015-04-10 16:10:05.7187|Error|System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SEModAPIInternal.API.Common.PowerManager.get_TotalPower()
2015-04-10 16:10:05.7187|Error|Failed to get entity field '=F3vjA1VbQZ6h5a0yRFs7eUEDKm='
2015-04-10 16:10:05.7392|Error|System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SEModAPIInternal.API.Entity.BaseObject.GetEntityField(Object gameEntity, String fieldName)
2015-04-10 16:10:05.7392|Error|System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SEModAPIInternal.API.Common.PowerManager.get_TotalPower()
2015-04-10 16:10:05.7529|Error|Failed to get entity method 'get_TotalRequiredInput': Game entity was null
2015-04-10 16:10:05.7529|Error|System.Exception: Game entity was null
   bei SEModAPIInternal.API.Entity.BaseObject.GetEntityMethod(Object gameEntity, String methodName)
2015-04-10 16:10:05.7529|Error|System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SEModAPIInternal.API.Entity.BaseObject.InvokeEntityMethod(Object gameEntity, String methodName, Object[] parameters, Type[] argTypes)
   bei SEModAPIInternal.API.Common.PowerManager.get_AvailablePower()
2015-04-10 16:10:05.7734|Error|Failed to get entity field '=F3vjA1VbQZ6h5a0yRFs7eUEDKm='
2015-04-10 16:10:05.7734|Error|System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SEModAPIInternal.API.Entity.BaseObject.GetEntityField(Object gameEntity, String fieldName)
2015-04-10 16:10:05.7734|Error|System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SEModAPIInternal.API.Common.PowerManager.get_TotalPower()

**Comment by dodexahedron** [comment]
I still don't understand why you'd be getting this exception.
Can you provide me a copy of your Sandbox.Game.dll and Sandbox.Common.dll files?
I have a feeling this may be localization-related, since those fields exist in the game, for me, but it's clearly claiming they don't, for you.

**Comment by fo0** [comment]
Hi, yes sure. In adding the Timed-Cleaning get crazy tonight, and executing itself every SECOND.
I attached your wanted files + logs to the zip (7zip).

Link: http://jksl.de/thomas/Logs.7z

**Comment by zrisher** [comment]
I suggest this issue be renamed to "Selecting concealed entity in Entities Window causes NullReferenceException"

**Comment by zrisher** [comment]
Since dynamic conceal is a feature of Essentials and not Extender, could this be considered a duplicate of https://github.com/SEServerExtender/EssentialsPlugin/issues/5?

**Comment by dodexahedron** [comment]
Yes. That name describes the problem much better, and yes, this is a duplicate.

Closing in favor of SEServerExtender/EssentialsPlugin#5

**Comment by dodexahedron** [comment]
Actually...
On second thought, I won't close this one until it is fixed, because the issue really is in extender, even though the thing that gets it into that state to begin with is essentials.
Extender itself is what is throwing the error, because it apparently doesn't know how to deal with concealed entities properly.

Re-opening.

**Comment by Ragnar24** [comment]
Just to let you know, I received this error today as well after updating my essentials and extender. It's not too big of an issue, but what may be concerning is that when I have the chat log of extender open my UPS is at a solid 60. When I look into the entities list, my UPS drops immediately to 28-32. Is this normal? If you would like me to upload my files, just let me know which ones.

**Comment by dodexahedron** [comment]
The entities tab is a heavy place to be, because it's constantly updating the list, which means calls to particularly heavy methods in the game.  You definitely shouldn't leave Extender on that tab if you're not actively using it.
I've got a plan for how to fix the concealed entity causing crash bug, but it needs to wait on something else more significant I'm doing to the underlying code.

**Comment by Ragnar24** [comment]
Ah ok. That is good to know. Once again thanks for your hard work.

**Comment by dodexahedron** [comment]
This is resolved in SESE v1.79.08.411.
Closing.
