### ISSUE TITLE
Error starting the Sever Extender post 1.0.93 hotfix update.

### ISSUE THREAD

**Issue by markam67** [SEServerExtender/SEServerExtender#82]
2015-07-31 19:35:48.1636|Info|Starting SEServerExtender with 3 arguments: instance=Last One Died New DX11 Survival World
        autosave=10
        instancepath=C:\ProgramData\SpaceEngineersDedicated\Last One Died New DX11 Survival World
2015-07-31 19:35:48.5364|Info|Finished loading SandboxGameAssemblyWrapper
2015-07-31 19:35:48.7364|Info|All main types passed reflection unit tests!
2015-07-31 19:35:48.7594|Info|All entity types passed reflection unit tests!
2015-07-31 19:35:48.7974|Info|All block types passed reflection unit tests!
2015-07-31 19:35:48.7974|Info|Finished creating server!
2015-07-31 19:35:48.8162|Info|Finished loading DedicatedServerAssemblyWrapper
2015-07-31 19:35:48.8162|Info|Finished loading PluginManager
2015-07-31 19:35:48.8162|Info|Finished loading FactionsManager
2015-07-31 19:35:48.8250|Info|Finished loading EntityEventManager
2015-07-31 19:35:48.8401|Info|Finished loading ChatManager
2015-07-31 19:35:48.8401|Info|Common instance pre-selected: 'Last One Died New DX11 Survival World'
2015-07-31 19:35:48.8401|Info|Autosave interval: 10
2015-07-31 19:35:48.8401|Info|Full path pre-selected: 'C:\ProgramData\SpaceEngineersDedicated\Last One Died New DX11 Survival World'
2015-07-31 19:35:48.8401|Info|end parsing
2015-07-31 19:35:48.8401|Info|Opening up WCF service listener at http://localhost:5353/ServerService/Last One Died New DX11 Survival World
2015-07-31 19:36:08.0530|Info|Loading Session Settings
2015-07-31 19:36:09.0374|Info|
Max Players: 8
2015-07-31 19:36:09.0374|Info|OnlineMode: PUBLIC
2015-07-31 19:36:09.0530|Info|GameMode: Survival
2015-07-31 19:36:09.0530|Info|Scenario: Asteroids
2015-07-31 19:36:09.0530|Info|World Size: 0

Space Engineers  01_093_012
Is official: True [NO]
Environment.Is64BitProcess: True
2015-07-31 19:36:09.3030|Info|Finished loading PlayerManager
2015-07-31 19:36:09.3030|Info|Finished loading NetworkManager
2015-07-31 19:36:10.146: Bind IP : 0.0.0.0:27016
Setting breakpad minidump AppID = 244850
2015-07-31 19:36:12.134: Server successfully started
2015-07-31 19:36:12.134: Product name: Space Engineers
2015-07-31 19:36:12.134: Desc: Space Engineers
2015-07-31 19:36:12.135: Public IP: 
2015-07-31 19:36:12.137: Steam ID: 
2015-07-31 19:36:13.1660|Info|Finished loading PlayerMap
2015-07-31 19:36:13.603: Server connected to Steam
2015-07-31 19:36:13.604: Server PolicyResponse (1)
2015-07-31 19:36:29.846: Unable to download mods
2015-07-31 19:36:30.1956|Info|Loading plugins ...
2015-07-31 19:36:30.2016|Info|Scanning: C:\ProgramData\SpaceEngineersDedicated\Last One Died New DX11 Survival World\Mods
2015-07-31 19:36:30.2016|Info|Finished loading plugins
2015-07-31 19:36:30.2147|Info|Initializing plugins ...
2015-07-31 19:36:30.2147|Info|Finished initializing plugins
2015-07-31 19:36:33.0193|Error|System.NullReferenceException: Object reference not set to an instance of an object.
   at SEServerExtender.SEServerExtender.FactionRefresh(Object sender, EventArgs e)
2015-07-31 19:36:38.0109|Error|System.NullReferenceException: Object reference not set to an instance of an object.
   at SEServerExtender.SEServerExtender.FactionRefresh(Object sender, EventArgs e)
2015-07-31 19:36:43.0184|Error|System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by afinegan** [comment]
I think steam isn't allowing any of us to download mods, im getting the same error (were the same version of extender was working perfectly fine 1 hour before)

**Comment by afinegan** [comment]
I take that back:
I *too" have recieved the:
2015-07-31 19:36:33.0193|Error|System.NullReferenceException: Object reference not set to an instance of an object.
at SEServerExtender.SEServerExtender.FactionRefresh(Object sender, EventArgs e)
2015-07-31 19:36:38.0109|Error|System.NullReferenceException: Object reference not set to an instance of an object.
at SEServerExtender.SEServerExtender.FactionRefresh(Object sender, EventArgs e)
2015-07-31 19:36:43.0184|Error|System.NullReferenceException: Object reference not set to an instance of an object.

Had to revert a save 2 hrs back - almost like something corrupting the save.

**Comment by dodexahedron** [comment]
I don't suppose you still have a complete copy of the world before reverting to a backup?

**Comment by afinegan** [comment]
I do, but I have to send it to you private for obvious reasons - I can include the mod list for you also (if any of that matters)
andrew.finegan at gmail dot com

**Comment by markam67** [comment]
Interestingly I ran the saves using the Keen dedicated server last night and now I am running them using the SESE again and now I do not get the issue???? Very strange bug whatever it was. I was going to offer my save games but clearly they no longer have the issue at this time.

**Comment by tdmike** [comment]
Both my modded and vanilla server just booted up without any problems, the modded server has over 120+ mods in it.

**Comment by dodexahedron** [comment]
This was a Steam issue.
Resolving this.
Note that I don't currently have a good way of knowing if it has or hasn't been successful.
