### ISSUE TITLE
New error when using 1.094 update

### ISSUE THREAD

**Issue by markam67** [SEServerExtender/SEServerExtender#84]
2015-08-06 18:34:15.066: An error occurred while adding one or more objects. See log file for more details.
2015-08-06 18:34:15.857: Session loaded
2015-08-06 18:34:22.7271|Info|Loading plugins ...
2015-08-06 18:34:22.7301|Info|Scanning: C:\ProgramData\SpaceEngineersDedicated\Last One Died New DX11 Survival World\Mods
2015-08-06 18:34:22.7531|Info|Finished loading plugins
2015-08-06 18:34:22.7531|Info|Initializing plugins ...
2015-08-06 18:34:22.7631|Info|Initializing plugin at C:\ProgramData\SpaceEngineersDedicated\Last One Died New DX11 Survival World\Mods\Essentials\Essentials.dll - f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-08-06 18:34:22.7631|Debug|Initializing Essentials plugin at path C:\ProgramData\SpaceEngineersDedicated\Last One Died New DX11 Survival World\Mods\Essentials\
2015-08-06 18:34:22.8652|Info|Stopping all ships
2015-08-06 18:34:24.2442|Info|3 ships have been stopped
2015-08-06 18:34:24.2462|Info|Plugin 'Dedicated Server Essentials' initialized. (Version: 1.13.3.2452  ID: f767bda5-0a8c-4813-85fd-a5a2341778e8)
2015-08-06 18:34:24.2462|Info|Finished initializing plugins
2015-08-06 18:34:24.705: Game ready... Press Ctrl+C to exit
2015-08-06 18:34:24.8096|Error|Failed to get static method 'SendEntityCreated'
2015-08-06 18:34:24.8096|Error|System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at SEModAPIInternal.API.Entity.BaseObject.GetStaticMethod(Type objectType, String methodName)
2015-08-06 18:34:25.2773|Error|Failed to invoke static method 'SendEntityCreated': Method is empty
2015-08-06 18:34:25.2773|Error|System.Exception: Method is empty
   at SEModAPIInternal.API.Entity.BaseObject.InvokeStaticMethod(Type objectType, String methodName, Object[] parameters)

**Comment by tdmike** [comment]
Same here, doesnt seem to effect gameplay though

2015-08-07 00:53:29.2255|Error|System.Reflection.AmbiguousMatchException: Ambiguous match
found. at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)  at System.Type.GetMethod(String name, BindingFlags bindingAttr)  at SEModAPIInternal.API.Entity.BaseObject.GetStaticMethod(Type objectType, String methodName)
2015-08-07 00:53:29.2451|Error|Failed to invoke static method 'SendEntityCreated': Method is empty
2015-08-07 00:53:29.2451|Error|System.Exception: Method is empty at SEModAPIInternal.API.Entity.BaseObject.InvokeStaticMethod(Type objectType, String methodName, Object[] parameters)

**Comment by niapet** [comment]
I was able to start the server but the essentials commands don't seem to be responding.  For instance I typed /motd and the motd was not displayed.

I tried removing and reinstalling the essentials plugin; the motd still does not work.  I noticed other parts of the plugin are working as i accidental left the number on the block enforcement line i was writing at 0 and it deleted every drill on the server.  So perhaps there is an issue with the motd, or some system it uses to work?

edit: I just noticed i get the same error as when the server loads, the one described by the posters above, when I type /motd within the server.  No MoTD is displayed and the error is in the server console.

**Comment by tdmike** [comment]
essentials seems to be working fine here, although I don't use motd, restarting and backing up my saves works fine

**Comment by niapet** [comment]
Motd is not working, so essentials is not working fine, just some of it is working fine. I cant claim to understand what the error is saying, but it looks like an error getting entities, possibly players.  This could be a bad thing.

**Comment by tdmike** [comment]
From what I can tell this error has nothing to do with Essentials, it seems to be a internal error of ServerExtender. According to https://github.com/SEServerExtender/EssentialsPlugin/issues/44 motd has been broken for while now...

**Comment by niapet** [comment]
Hmm is this internal error causing Essentials to be unable to display the motd to players?  Does anyone else use this function and can confirm they are having a problem with it too?

I should probably add that other actions that interact with players via text fail to run as well.  For instance the /f command doesn't work.

**Comment by tdmike** [comment]
Motd had been bugging for over two months now, I personally gave up about a month ago. I don't think this causing it but let's wait for dodexahedron

**Comment by MescalineMonkey** [comment]
I'm getting the same error in my server.

Faction chat not working.
Server waypoints are not working.
/motd command does not work.

**Comment by dodexahedron** [comment]
This is fixed in https://github.com/SEServerExtender/SEServerExtender/releases/tag/v1.97.08.567-alpha
