### ISSUE TITLE
Can't start Server Extender

### ISSUE THREAD

**Issue by ZilgornZeypher** [SEServerExtender/SEServerExtender#85]
It shows me this when I try to start the program
2015-08-21 12:00:20.7879|Info|SEServerExtender.Program.Start|Starting SEServerExtender with 0 arguments: 
2015-08-21 12:00:22.4753|Info|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper..ctor|Finished loading SandboxGameAssemblyWrapper
2015-08-21 12:00:25.5065|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|All main types passed reflection unit tests!
2015-08-21 12:00:25.8034|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|All entity types passed reflection unit tests!
2015-08-21 12:00:26.0064|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|All block types passed reflection unit tests!
2015-08-21 12:00:26.0534|Info|SEModAPIExtensions.API.Server..ctor|Finished creating server!
2015-08-21 12:00:26.1003|Info|SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.get_Instance|Finished loading DedicatedServerAssemblyWrapper
2015-08-21 12:00:26.1159|Info|SEModAPIExtensions.API.PluginManager..ctor|Finished loading PluginManager
2015-08-21 12:00:26.1159|Info|SEModAPIInternal.API.Common.FactionsManager.get_Instance|Finished loading FactionsManager
2015-08-21 12:00:26.1315|Info|SEModAPIInternal.API.Common.EntityEventManager.get_Instance|Finished loading EntityEventManager
2015-08-21 12:00:26.1783|Info|SEModAPIExtensions.API.ChatManager..ctor|Finished loading ChatManager
2015-08-21 12:00:26.2721|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|end parsing
2015-08-21 12:00:26.2721|Info|SEServerExtender.Program.Start|Opening up WCF service listener at http://localhost:5353/ServerService/
2015-08-21 12:00:31.1626|Error|SEModAPI.API.GameInstallationInfo.GetServiceInstallPath|AppDomain.UnhandledException - System.Security.SecurityException: Requested registry access is not allowed.
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at SEModAPI.API.GameInstallationInfo.GetServiceInstallPath(String serviceName)
   at SEModAPI.API.GameInstallationInfo.GetCommonInstanceList()
   at SEServerExtender.SEServerExtender.SetupControls()
   at SEServerExtender.SEServerExtender..ctor(Server server)
   at SEServerExtender.Program.StartGui()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
The Zone of the assembly that failed was:
MyComputer

**Comment by markam67** [comment]
Are you starting the game using Run as Administrator? You need to right click on the icon and use the run as administrator option. You can also right click and select properties and then compatibility and click the run as administrator box.

**Comment by ZilgornZeypher** [comment]
Yes I am running it as Administrator for both Server extender and the basic server tool.

**Comment by dodexahedron** [comment]
Right-click on the zip file before you extract it and click properties.  Then, click the "unblock" button in the properties window.  Then extract it and run it.

**Comment by ZilgornZeypher** [comment]
I don't have unblock as an option under properties. I'm trying to run this on Windows server 2012.

I have updated to the lastes versions of dedicated server and server extender and still have the same error log

**Comment by ZilgornZeypher** [comment]
I have done some testing I can start Server extender on my personal PC running windows 10 however  no matter what I do I can't seem to get it working on Windows server 2012

**Comment by McyD** [comment]
Make sure .net framework is completely updated, that was the issue I had.

**Comment by ZilgornZeypher** [comment]
double checked my .net framework I have 3.5 and 4.5 installed and up to date. I just added 3.5 to the server today and still crashes with the same error

**Comment by ZilgornZeypher** [comment]
Anyone else got any suggestions? I'd be willing to give them a go. It's painful not having the extender automated backup or all it's other nice features.

**Comment by ZilgornZeypher** [comment]
Udated to version 573 and now have a new error 

2015-09-24 16:55:17.3347|Info|Starting SEServerExtender with 0 arguments:
2015-09-24 16:55:17.5427|Info|Finished loading SandboxGameAssemblyWrapper
2015-09-24 16:55:17.5927|Error|System.Exception: Could not find internal type for PowerManager
   at SEModAPIInternal.API.Common.PowerManager.ReflectionUnitTest()
2015-09-24 16:55:17.5927|Warn|PowerManager reflection validation failed!
2015-09-24 16:55:17.7437|Info|Exception - {0}
    |System.TypeLoadException: Could not load type 'Sandbox.ModAPI.Ingame.IMyPow
erProducer' from assembly 'Sandbox.Common, Version=1.0.0.0, Culture=neutral, Pub
licKeyToken=null'.
   at SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests()

   at SEModAPIExtensions.API.BasicUnitTestManager.Run()
   at SEServerExtender.Program.Start(String[] args)

**Comment by McyD** [comment]
@ZilgornZeypher
updating to 573 is unrelated, keen changed something in today's update and broke SE extender.  see the newest issue.

**Comment by cccdemon** [comment]
Operation System Windows 2012 R2 - Same issue - why are you iterate over registry entries you dont need? 
What are you searchin for? 
(The Zone of the assembly that failed was:
MyComputer)

(related to security exception)..
Everytime SESE gots an update i have to patch this -.-
