### ISSUE TITLE
SESE Crash after latest update

### ISSUE THREAD

**Issue by Cryptonat** [SEServerExtender/SEServerExtender#97]
Error log is as follows: (Could not attach text file due to txt files not being permitted)

2015-10-22 17:16:01.5001|Info|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper..ctor|Finished loading SandboxGameAssemblyWrapper
2015-10-22 17:16:01.5161|Error|SEModAPIInternal.API.Server.ServerNetworkManager.ReflectionUnitTest|System.TypeLoadException: Could not find internal type for AttachToCockpitMsg
   at SEModAPIInternal.API.Server.ServerNetworkManager.ReflectionUnitTest()
    |System.TypeLoadException: Could not find internal type for AttachToCockpitMsg
   at SEModAPIInternal.API.Server.ServerNetworkManager.ReflectionUnitTest()
2015-10-22 17:16:01.5161|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|ServerNetworkManager reflection validation failed!
2015-10-22 17:16:01.6321|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'SendRemovedBlocks' in type 'Sandbox.Game.Multiplayer.MySyncGrid'
2015-10-22 17:16:01.6321|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'BuildBlocksSuccess' in type 'Sandbox.Game.Multiplayer.MySyncGrid'
2015-10-22 17:16:01.6321|Error|SEModAPI.API.Utility.Reflection.HasField|Failed to find field 'm_destroyBlockQueue' in type 'Sandbox.Game.Multiplayer.MySyncGrid'
2015-10-22 17:16:01.6401|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|CubeGridNetworkManager reflection validation failed!
2015-10-22 17:16:01.6401|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridThrusterManager.ReflectionUnitTest|System.Exception: Could not find type for CubeGridThrusterManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridThrusterManager.ReflectionUnitTest()
    |System.Exception: Could not find type for CubeGridThrusterManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGridThrusterManager.ReflectionUnitTest()
2015-10-22 17:16:01.6401|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|CubeGridThrusterManager reflection validation failed!
2015-10-22 17:16:01.6611|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'set_RemainingCapacity' in type 'Sandbox.Game.GameSystems.Electricity.MyBattery'
2015-10-22 17:16:01.6611|Error|SEModAPI.API.Utility.Reflection.HasField|Failed to find field 'm_remainingCapacity' in type 'Sandbox.Game.GameSystems.Electricity.MyBattery'
2015-10-22 17:16:01.6611|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|CharacterEntity reflection validation failed!
2015-10-22 17:16:01.7181|Error|SEModAPI.API.Utility.Reflection.HasField|Failed to find field 'm_batteryBlockDefinition' in type 'Sandbox.Game.Entities.MyBatteryBlock'
2015-10-22 17:16:01.7181|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|BatteryBlockEntity reflection validation failed!
2015-10-22 17:16:01.7421|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'SetThrustOverride' in type 'Sandbox.Game.Entities.MyThrust'
2015-10-22 17:16:01.7421|Error|SEModAPI.API.Utility.Reflection.HasField|Failed to find field 'SyncObject' in type 'Sandbox.Game.Entities.MyThrust'
2015-10-22 17:16:01.7421|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|ThrustEntity reflection validation failed!
2015-10-22 17:16:01.7491|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ThrustNetworkManager.ReflectionUnitTest|System.Exception: Could not find network manager type for ThrustEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ThrustNetworkManager.ReflectionUnitTest()
    |System.Exception: Could not find network manager type for ThrustEntity
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.ThrustNetworkManager.ReflectionUnitTest()
2015-10-22 17:16:01.7491|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|ThrustNetworkManager reflection validation failed!
2015-10-22 17:16:01.7731|Error|SEModAPI.API.Utility.Reflection.HasField|Failed to find field 'm_ammoInventory' in type 'Sandbox.Game.Weapons.MyLargeTurretBase'
2015-10-22 17:16:01.7731|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|TurretBaseEntity reflection validation failed!
2015-10-22 17:16:01.7861|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'set_MaxPowerOutput' in type 'Sandbox.Game.Entities.MyReactor'
2015-10-22 17:16:01.7861|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|ReactorEntity reflection validation failed!
2015-10-22 17:16:01.7861|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'set_MaxPowerOutput' in type 'Sandbox.Game.Entities.Blocks.MySolarPanel'
2015-10-22 17:16:01.7861|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|SolarPanelEntity reflection validation failed!
2015-10-22 17:16:01.8021|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'get_Velocity' in type 'Sandbox.Game.Entities.Blocks.MyPistonBase'
2015-10-22 17:16:01.8021|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'set_Velocity' in type 'Sandbox.Game.Entities.Blocks.MyPistonBase'
2015-10-22 17:16:01.8021|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'get_MinLimit' in type 'Sandbox.Game.Entities.Blocks.MyPistonBase'
2015-10-22 17:16:01.8021|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'set_MinLimit' in type 'Sandbox.Game.Entities.Blocks.MyPistonBase'
2015-10-22 17:16:01.8021|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'get_MaxLimit' in type 'Sandbox.Game.Entities.Blocks.MyPistonBase'
2015-10-22 17:16:01.8021|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to find method 'set_MaxLimit' in type 'Sandbox.Game.Entities.Blocks.MyPistonBase'
2015-10-22 17:16:01.8021|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|PistonEntity reflection validation failed!
2015-10-22 17:16:01.8121|Error|SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.PistonNetworkManager.ReflectionUnitTest|System.Exception: Could not find internal type for PistonNetworkManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.PistonNetworkManager.ReflectionUnitTest()
    |System.Exception: Could not find internal type for PistonNetworkManager
   at SEModAPIInternal.API.Entity.Sector.SectorObject.CubeGrid.CubeBlock.PistonNetworkManager.ReflectionUnitTest()
2015-10-22 17:16:01.8121|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|PistonNetworkManager reflection validation failed!
2015-10-22 17:16:01.8371|Info|SEModAPIExtensions.API.Server..ctor|Finished creating server!
2015-10-22 17:16:01.8501|Info|SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.get_Instance|Finished loading DedicatedServerAssemblyWrapper
2015-10-22 17:16:01.8571|Info|SEModAPIExtensions.API.PluginManager..ctor|Finished loading PluginManager
2015-10-22 17:16:01.8571|Info|SEModAPIInternal.API.Common.FactionsManager.get_Instance|Finished loading FactionsManager
2015-10-22 17:16:01.8571|Info|SEModAPIInternal.API.Common.EntityEventManager.get_Instance|Finished loading EntityEventManager
2015-10-22 17:16:01.8921|Info|SEModAPIExtensions.API.ChatManager..ctor|Finished loading ChatManager
2015-10-22 17:16:01.8921|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|Auto-Start enabled
2015-10-22 17:16:01.8921|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|Common instance pre-selected: 'SEPublic2'
2015-10-22 17:16:01.8921|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|Full path pre-selected: 'C:\ProgramData\SpaceEngineersDedicated\SEPublic2'
2015-10-22 17:16:01.8921|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|Restart On Crash: Enabled
2015-10-22 17:16:01.8921|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|end parsing
2015-10-22 17:16:02.4481|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|Loading Session Settings
2015-10-22 17:16:09.3975|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|
Max Players: 32
2015-10-22 17:16:09.3975|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|OnlineMode: PUBLIC
2015-10-22 17:16:09.3975|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|GameMode: Survival
2015-10-22 17:16:09.3975|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|Scenario: Asteroids
2015-10-22 17:16:09.4085|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|World Size: 155

2015-10-22 17:16:09.4085|Info|SEServerExtender.Program.Start|Opening up WCF service listener at http://localhost:5353/ServerService/SEPublic2
2015-10-22 17:16:15.7129|Info|SEServerExtender.SEServerExtender.ChatViewRefresh|Finished loading PlayerManager
2015-10-22 17:16:15.7129|Info|SEServerExtender.SEServerExtender.ChatViewRefresh|Finished loading NetworkManager
2015-10-22 17:16:15.7129|Info|SEModAPIInternal.API.Common.PlayerMap.get_Instance|Finished loading PlayerMap
2015-10-22 17:16:39.8443|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Loading plugins ...
2015-10-22 17:16:39.8443|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Scanning: C:\ProgramData\SpaceEngineersDedicated\SEPublic2\Mods
2015-10-22 17:16:39.8643|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Finished loading plugins
2015-10-22 17:16:39.8643|Info|SEModAPIExtensions.API.PluginManager.Init|Initializing plugins ...
2015-10-22 17:16:39.8763|Info|SEModAPIExtensions.API.PluginManager.InitPlugin|Initializing plugin at C:\ProgramData\SpaceEngineersDedicated\SEPublic2\Mods\Essentials\Essentials.dll - f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-10-22 17:16:41.2564|Info|SEModAPIExtensions.API.Server.RunServer|Server has stopped running
2015-10-22 17:16:44.7286|Error|SEServerExtender.SEServerExtender.FactionRefresh|System.NullReferenceException: Object reference not set to an instance of an object.
   at SEServerExtender.SEServerExtender.FactionRefresh(Object sender, EventArgs e)
    |System.NullReferenceException: Object reference not set to an instance of an object.
   at SEServerExtender.SEServerExtender.FactionRefresh(Object sender, EventArgs e)

**Comment by Devlah** [comment]
A quick glance at this error log reveals that it is similar to my own.  Windows error dialog box appears indicating log file is in use by another process.  But otherwise, same results as above.

**Comment by wweiland** [comment]
Is the project dying :(

**Comment by wweiland** [comment]
Fresh would and now mine starts w/ SESE

**Comment by wweiland** [comment]
Sorry, world
