### ISSUE TITLE
Since 1.116 weird error messages appearing in console window

### ISSUE THREAD

**Issue by markam67** [SEServerExtender/SEServerExtender#99]
Here is what I am seeing.

MySandboxGame.LoadData() - END
2016-01-07 19:05:11.356 - Thread:   9 ->     ERROR: Exception during objectbuilder read! (xml): MyObjectBuilder_Checkpoint
2016-01-07 19:05:11.356 - Thread:   9 ->     Exception occured: System.InvalidOperationException: There is an error in XML document (41, 53). ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read66_SerializableDefinitionId(Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read689_Item(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read272_Slot(Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read273_MyObjectBuilder_Toolbar(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read629_MyObjectBuilder_Checkpoint(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1232_MyObjectBuilder_Checkpoint()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VRage.ObjectBuilders.MyObjectBuilderSerializer.DeserializeXML(Stream reader, MyObjectBuilder_Base& objectBuilder, Type builderType)
2016-01-07 19:05:11.356 - Thread:   9 ->     InnerException: 
2016-01-07 19:05:11.360 - Thread:   9 ->     Exception occured: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read66_SerializableDefinitionId(Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read689_Item(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read272_Slot(Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read273_MyObjectBuilder_Toolbar(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read629_MyObjectBuilder_Checkpoint(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1232_MyObjectBuilder_Checkpoint()
2016-01-07 19:05:11.360 - Thread:   9 ->     Failed to deserialize file 'C:\ProgramData\SpaceEngineersDedicated\planets2\Saves\PLANETS 2\Sandbox.sbc'
2016-01-07 19:05:11.361 - Thread:   9 ->     This world can not be loaded. It has been created in newer version of the game.
2016-01-07 19:05:11.363 - Thread:   9 ->  MySandboxGame.Initialize() - END

**Comment by markam67** [comment]
I also noted that really the world was unable to load at all.

Thanks

**Comment by yajiedesign** [comment]
I also do so.
Try to repair the failed

**Comment by rexxar-tc** [comment]
Check the releases page, I posted a new one that works.

**Comment by markam67** [comment]
Thank you so much I really appreciate all the work on SESE it really is much better to manage servers than they KEEN basic DS
